<a href="https://colab.research.google.com/github/staniya/shibaki-RF-analysis/blob/main/RF%E8%A7%A3%E6%9E%90%E3%83%87%E3%83%A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# データの図を出力するライブラリ
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
%matplotlib inline

# 環境設定
import sys
sys.path.append('models')

# 実際の機械学習ライブラリ
import tensorflow as tf

In [2]:
# Google Driveからデータを引っ張ってくる
from google.colab import drive
drive.mount('/content/drive')
!cp '/content/drive/MyDrive/shibaki analysis/AE-FILD BAL patient_data.xlsx' patient_data.xlsx

Mounted at /content/drive

In [3]:
# openpyxlというエンジンを使用して、ExcelファイルをPandasのデータフレームとして読みこむ
!pip install openpyxl==2.6
import pandas as pd
AE_FILD_df = pd.read_excel('patient_data.xlsx', engine='openpyxl')

Collecting openpyxl==2.6
  Downloading openpyxl-2.6.0.tar.gz (172 kB)
     |████████████████████████████████| 172 kB 5.1 MB/s
Requirement already satisfied: jdcal in /usr/local/lib/python3.7/dist-packages (from openpyxl==2.6) (1.4.1)
Requirement already satisfied: et_xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl==2.6) (1.1.0)
Building wheels for collected packages: openpyxl
  Building wheel for openpyxl (setup.py) ... done
  Created wheel for openpyxl: filename=openpyxl-2.6.0-py2.py3-none-any.whl size=243902 sha256=e9959367097667be5a3c4a3a0a0924bcc4a798fe0676652d0ae9878ecd5add4b
  Stored in directory: /root/.cache/pip/wheels/4a/5e/2e/d6e53a8a4b88aa95509c0c94b5629a9f58bc1260d7315e6a92
Successfully built openpyxl
Installing collected packages: openpyxl
  Attempting uninstall: openpyxl
    Found existing installation: openpyxl 2.5.9
    Uninstalling openpyxl-2.5.9:
      Successfully uninstalled openpyxl-2.5.9
Successfully installed openpyxl-2.6.0

In [4]:
AE_FILD_df.head()

     No       ID  90day mortality\nsurvival:0\ndeath:1  ...  TNFb  VEGF    IL-36β
0  K003   558277                                     0  ...   3.2   3.2  4.221958
1  K022  1848827                                     0  ...   3.2   3.2  2.000000
2  K024  1902349                                     0  ...   3.2   3.2  2.000000
3  K043  3165531                                     0  ...   3.2   3.2  2.000000
4  K045  3253683                                     0  ...   3.2   3.2  2.000000

[5 rows x 64 columns]

In [5]:
# ヘルパーファンクションでテキスト内の"\n"をスペースに変換する
def clean_header(text):
  text = text.strip() # 最初と最後のスペースをテキストからとる
  text = text.replace(" ", "-")
  text_n_newline = text.replace("\n", " ")
  return text_n_newline

In [6]:
# ヘッダーコラムのテキストをリストとして変換する
AE_FILD_header_list = AE_FILD_df.columns.values.tolist()
AE_FILD_header_list

['No',
 'ID',
 '90day mortality\nsurvival:0\ndeath:1',
 'sex\nmale:0\nfemale:1',
 'age ',
 'smoking status\nNever:0\nEx(quit smoking over a year ago):1\nCurrent:2',
 'Brinkman Index',
 'emphysema\n(-):0\n(+):1',
 'Baseline ILD\nUIP:0\nprobable UIP:1\nIndeterminate for UIP:2\nAlternative diagnosis:3',
 'Collagen disease\n(-):0\n(+):1',
 'IPAF\n(-):0\n(+):1',
 'P/F ratio',
 'LDH',
 'CRP',
 'KL-6',
 '\nBAL(neutro %)',
 '\nBAL(Lymph %)',
 '\nBAL(Eos %)',
 '\nBAL(M %)',
 '\nBAL(CD4/8)',
 'MMP-1',
 'MMP-7',
 'TGFB1',
 'TGFB2',
 'TGFB3',
 'EGF',
 'FGF-2',
 'EOTAXIN',
 'TGF-a',
 'G-CSF',
 'Flt-3L',
 'GM-CSF',
 'FRACTALKINE',
 'IFN-a2',
 'IFN-g',
 'GRO',
 'IL-10',
 'MCP-3',
 'IL-12P40',
 'MDC',
 'IL-12P70',
 'IL-13',
 'IL-15',
 'sCD40L',
 'IL-17',
 'IL-1RA',
 'IL-1a',
 'IL-9',
 'IL-1b',
 'IL-2',
 'IL-3',
 'IL-4',
 'IL-5',
 'IL-6',
 'IL-7',
 'IL-8',
 'IP-10',
 'MCP-1',
 'MIP-1a',
 'MIP-1b',
 'TNFa',
 'TNFb',
 'VEGF',
 'IL-36β']

In [7]:
# 上記のヘッダーリストにclean_header()を応用する
AE_FILD_header_list_cleaned = [clean_header(x) for x in AE_FILD_header_list]
print(AE_FILD_header_list_cleaned)

['No', 'ID', '90day-mortality survival:0 death:1', 'sex male:0 female:1', 'age', 'smoking-status Never:0 Ex(quit-smoking-over-a-year-ago):1 Current:2', 'Brinkman-Index', 'emphysema (-):0 (+):1', 'Baseline-ILD UIP:0 probable-UIP:1 Indeterminate-for-UIP:2 Alternative-diagnosis:3', 'Collagen-disease (-):0 (+):1', 'IPAF (-):0 (+):1', 'P/F-ratio', 'LDH', 'CRP', 'KL-6', 'BAL(neutro-%)', 'BAL(Lymph-%)', 'BAL(Eos-%)', 'BAL(M-%)', 'BAL(CD4/8)', 'MMP-1', 'MMP-7', 'TGFB1', 'TGFB2', 'TGFB3', 'EGF', 'FGF-2', 'EOTAXIN', 'TGF-a', 'G-CSF', 'Flt-3L', 'GM-CSF', 'FRACTALKINE', 'IFN-a2', 'IFN-g', 'GRO', 'IL-10', 'MCP-3', 'IL-12P40', 'MDC', 'IL-12P70', 'IL-13', 'IL-15', 'sCD40L', 'IL-17', 'IL-1RA', 'IL-1a', 'IL-9', 'IL-1b', 'IL-2', 'IL-3', 'IL-4', 'IL-5', 'IL-6', 'IL-7', 'IL-8', 'IP-10', 'MCP-1', 'MIP-1a', 'MIP-1b', 'TNFa', 'TNFb', 'VEGF', 'IL-36β']

In [8]:
AE_FILD_df.columns = AE_FILD_header_list_cleaned
AE_FILD_df.head()

     No       ID  90day-mortality survival:0 death:1  ...  TNFb  VEGF    IL-36β
0  K003   558277                                   0  ...   3.2   3.2  4.221958
1  K022  1848827                                   0  ...   3.2   3.2  2.000000
2  K024  1902349                                   0  ...   3.2   3.2  2.000000
3  K043  3165531                                   0  ...   3.2   3.2  2.000000
4  K045  3253683                                   0  ...   3.2   3.2  2.000000

[5 rows x 64 columns]

In [9]:
# まず機械学習に不必要なコラムをdrop()する
AE_FILD_df = AE_FILD_df.drop(columns=["No"])
AE_FILD_df.head()

        ID  90day-mortality survival:0 death:1  ...  VEGF    IL-36β
0   558277                                   0  ...   3.2  4.221958
1  1848827                                   0  ...   3.2  2.000000
2  1902349                                   0  ...   3.2  2.000000
3  3165531                                   0  ...   3.2  2.000000
4  3253683                                   0  ...   3.2  2.000000

[5 rows x 63 columns]

In [10]:
# データセット内のNaN値をどうするか (まずはinputer transformで試してみる)
from sklearn.impute import SimpleImputer
AE_FILD_df.replace('NaN', np.NaN, inplace=True) # データフレーム内の"NaN"をnumpyのNaNと置き換える
imp = SimpleImputer(missing_values=np.NaN, strategy="median") # sklearnのSimpleImputerを使い、np.NaNをnull値として認識させる。加、strategy="median"はnp.NaNをその行のNaNを中央値と置き換えるための指定
AE_FILD_df_idf = pd.DataFrame(imp.fit_transform(AE_FILD_df))
AE_FILD_df_idf.columns = AE_FILD_df.columns # SimpleImputerは数値しか作成できない為、元のデータセットの行名を新しいデータセットに加るコード
df_null_val = list(AE_FILD_df_idf.isna().sum()) # データセット内にNaN値が無いかの確認
print(f"AE_FILD_df_idfデータフレーム内のNaN数：{df_null_val}")

AE_FILD_df_idfデータフレーム内のNaN数：[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [11]:
from collections import OrderedDict

columnname_dict = OrderedDict()
columnname_dict['90day-mortality'] = {"survival":0.0, "death":1.0}
columnname_dict['sex'] = {"male":0.0, "female":1.0}
columnname_dict['smoking-status'] = {"Never":0.0, 'Ex(quit smoking over a year ago)':1.0, "Current":2.0}
columnname_dict['emphysema'] = {"-":0.0, "+":1.0}
columnname_dict['Baseline-ILD'] =  {"UIP":0.0, "probable UIP":1.0, "Indeterminate for UIP":2.0, "Alternative diagnosis":3.0}
columnname_dict['Collagen-disease'] = {"-":0.0, "+":1.0}
columnname_dict['IPAF'] = {"-":0.0, "+":1.0}

for key,values in columnname_dict.items():
  temp_dict = {}
  for k,v in values.items():
    temp_dict[v] = k
    columnname_dict[key] = temp_dict

columnname_dict

OrderedDict([('90day-mortality', {0.0: 'survival', 1.0: 'death'}),
             ('sex', {0.0: 'male', 1.0: 'female'}),
             ('smoking-status',
              {0.0: 'Never',
               1.0: 'Ex(quit smoking over a year ago)',
               2.0: 'Current'}),
             ('emphysema', {0.0: '-', 1.0: '+'}),
             ('Baseline-ILD',
              {0.0: 'UIP',
               1.0: 'probable UIP',
               2.0: 'Indeterminate for UIP',
               3.0: 'Alternative diagnosis'}),
             ('Collagen-disease', {0.0: '-', 1.0: '+'}),
             ('IPAF', {0.0: '-', 1.0: '+'})])

In [12]:
# ヘルパーファンクションでテキスト内の記号と置き換える
def remove_header_map(text):
  for key in columnname_dict.keys():
    if key in text:
      text = key
  return text

# ヘッダーコラムのテキストをリストとして変換する
AE_FILD_header_list = AE_FILD_df_idf.columns.values.tolist()
AE_FILD_header_list_cleaned = [remove_header_map(x) for x in AE_FILD_header_list]
AE_FILD_df_idf.columns = AE_FILD_header_list_cleaned
AE_FILD_df_idf.head()

          ID  90day-mortality  sex   age  ...       TNFa  TNFb  VEGF    IL-36β
0   558277.0              0.0  0.0  78.0  ...   4.483265   3.2   3.2  4.221958
1  1848827.0              0.0  1.0  72.0  ...  24.074274   3.2   3.2  2.000000
2  1902349.0              0.0  0.0  86.0  ...   8.748703   3.2   3.2  2.000000
3  3165531.0              0.0  0.0  58.0  ...   3.792897   3.2   3.2  2.000000
4  3253683.0              0.0  0.0  76.0  ...  21.233261   3.2   3.2  2.000000

[5 rows x 63 columns]

In [13]:
# for columns in AE_FILD_df_idf.columns:
#     for key,value in columnname_dict.items():
#       if columns == key:
#         AE_FILD_df_idf[columns].replace(value,inplace=True)
# AE_FILD_df_idf.head()

In [14]:
# 模擬データを作るため、DataSynthesizer ライブラリーの導入
!pip install DataSynthesizer
from DataSynthesizer.DataDescriber import DataDescriber
from DataSynthesizer.DataGenerator import DataGenerator
from DataSynthesizer.ModelInspector import ModelInspector
from DataSynthesizer.lib.utils import read_json_file, display_bayesian_network

Collecting DataSynthesizer
  Downloading DataSynthesizer-0.1.10-py2.py3-none-any.whl (24 kB)
Requirement already satisfied: seaborn>=0.10.1 in /usr/local/lib/python3.7/dist-packages (from DataSynthesizer) (0.11.2)
Requirement already satisfied: scikit-learn>=0.23.1 in /usr/local/lib/python3.7/dist-packages (from DataSynthesizer) (1.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.7/dist-packages (from DataSynthesizer) (1.1.5)
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.7/dist-packages (from DataSynthesizer) (3.2.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.7/dist-packages (from DataSynthesizer) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.7/dist-packages (from DataSynthesizer) (1.19.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.2->DataSynthesizer) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.2->DataSynthesizer) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.2->DataSynthesizer) (3.0.6)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.5->DataSynthesizer) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.8.1->DataSynthesizer) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.23.1->DataSynthesizer) (3.0.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.23.1->DataSynthesizer) (1.1.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.23.1->DataSynthesizer) (1.4.1)
Installing collected packages: DataSynthesizer
Successfully installed DataSynthesizer-0.1.10

In [15]:
import os
# 上で作成したPandasのデータフレームをDataSynthesizerが応用できるようにcsvに変換する
AE_FILD_df_idf.to_csv("AE_FILD_df_idf.csv", index=False)

# 模擬データが元のデータの類似するように模擬データの作成設定をcorrelated_attribute_modeにする
mode = 'correlated_attribute_mode'

# 模擬データの構造を説明するための情報ファイル等の指定
os.makedirs("./out") # 出力ディレクトリーの作成
os.makedirs(f"./out/{mode}") # 模擬データのモード名を元にサブ出力ディレクトリーの作成
description_file = f'./out/{mode}/description.json'
synthetic_data = f'./out/{mode}/sythetic_data.csv'

In [16]:
categorical_attributes = {}

# データフレーム内の0−9行の内age以外の行はカテゴリカルなため、模擬データを作成出来るようにカテゴリかルアトリビュートとして認識する
for columns in list(AE_FILD_df_idf.columns[:9]):
  if columns != 'ID' and columns != 'age':
    categorical_attributes[columns] = True
# データの要素を識別できるように、IDをデータのキーとして認識する
candidate_keys = {'ID': True}

# OrderedDictがちゃんと作成されているか確認するコード
for key, val in categorical_attributes.items():
  print(f"{key}: {val}")

90day-mortality: True
sex: True
smoking-status: True
Brinkman-Index: True
emphysema: True
Baseline-ILD: True
Collagen-disease: True

In [17]:
# ドメインサイズがこのしきい値よりも小さい場合、属性はカテゴリーに分類されます。
# 今回のデータでは一番多いカテゴリー要素が4だったので、閾値を4と指定する
threshold_value = 4

# 差分プライバシーのパラメーター。 これは、入力データセットの行を削除しても、exp（epsilon）の乗法差以上に同じ出力を取得する確率が変わらないことを大まかに意味します。 
# イプシロン値を増やすことで学習モデルのノイズを減らせます。 差分プライバシーをオフにするにはepsilon = 0を設定します。
epsilon = 1

# ベイジアンネットワーク内の親ノードの最大数、つまり、有向グラフでの入力エッジの最大数。
degree_of_bayesian_network = 3

# DataDescriberをインスタンス化する
describer = DataDescriber(category_threshold=threshold_value)

# データセットの統計を計算する
describer.describe_dataset_in_correlated_attribute_mode(dataset_file='./AE_FILD_df_idf.csv', 
                                                        epsilon=epsilon, 
                                                        k=degree_of_bayesian_network,
                                                        attribute_to_is_categorical=categorical_attributes,
                                                        attribute_to_is_candidate_key=candidate_keys)

================ Constructing Bayesian Network (BN) ================
Adding ROOT MCP-1
Adding attribute GRO
Adding attribute IL-1a
Adding attribute IL-12P40
Adding attribute IFN-a2
Adding attribute FGF-2
Adding attribute IL-15
Adding attribute EOTAXIN
Adding attribute MIP-1a
Adding attribute VEGF
Adding attribute TGFB1
Adding attribute IL-3
Adding attribute GM-CSF
Adding attribute IL-10
Adding attribute MIP-1b
Adding attribute smoking-status
Adding attribute Brinkman-Index
Adding attribute 90day-mortality
Adding attribute IL-5
Adding attribute IL-1b
Adding attribute IL-7
Adding attribute IL-36β
Adding attribute IL-9
Adding attribute TGFB3
Adding attribute IL-17
Adding attribute Collagen-disease
Adding attribute MCP-3
Adding attribute IPAF
Adding attribute TNFa
Adding attribute TGF-a
Adding attribute MMP-1
Adding attribute BAL(neutro-%)
Adding attribute IL-1RA
Adding attribute TGFB2
Adding attribute FRACTALKINE
Adding attribute sex
Adding attribute MDC
Adding attribute IFN-g
Adding attribute IL-12P70
Adding attribute IP-10
Adding attribute IL-13
Adding attribute BAL(Eos-%)
Adding attribute BAL(CD4/8)
Adding attribute sCD40L
Adding attribute emphysema
Adding attribute Flt-3L
Adding attribute IL-2
Adding attribute P/F-ratio
Adding attribute Baseline-ILD
Adding attribute BAL(Lymph-%)
Adding attribute BAL(M-%)
Adding attribute G-CSF
Adding attribute MMP-7
Adding attribute TNFb
Adding attribute age
Adding attribute CRP
Adding attribute LDH
Adding attribute IL-6
Adding attribute EGF
Adding attribute IL-4
Adding attribute IL-8
========================== BN constructed ==========================

In [18]:
# データセットの統計を上で定義した出力ファイルに保存する
# その後に作成されたベイズネットワークを出力する
describer.save_dataset_description_to_file(description_file)
display_bayesian_network(describer.bayesian_network)

Constructed Bayesian network:
    GRO              has parents ['MCP-1'].
    IL-1a            has parents ['GRO', 'MCP-1'].
    IL-12P40         has parents ['GRO', 'IL-1a', 'MCP-1'].
    IFN-a2           has parents ['IL-1a', 'IL-12P40', 'GRO'].
    FGF-2            has parents ['IL-1a', 'IFN-a2', 'MCP-1'].
    IL-15            has parents ['IL-12P40', 'IFN-a2', 'MCP-1'].
    EOTAXIN          has parents ['IL-1a', 'IL-12P40', 'GRO'].
    MIP-1a           has parents ['IL-1a', 'EOTAXIN', 'MCP-1'].
    VEGF             has parents ['GRO', 'MIP-1a', 'MCP-1'].
    TGFB1            has parents ['IFN-a2', 'FGF-2', 'GRO'].
    IL-3             has parents ['IFN-a2', 'EOTAXIN', 'IL-1a'].
    GM-CSF           has parents ['EOTAXIN', 'VEGF', 'IFN-a2'].
    IL-10            has parents ['FGF-2', 'TGFB1', 'MCP-1'].
    MIP-1b           has parents ['FGF-2', 'MIP-1a', 'IL-1a'].
    smoking-status   has parents ['IFN-a2', 'IL-10', 'GRO'].
    Brinkman-Index   has parents ['GM-CSF', 'MIP-1b', 'EOTAXIN'].
    90day-mortality  has parents ['IL-3', 'smoking-status', 'MIP-1a'].
    IL-5             has parents ['TGFB1', 'smoking-status', 'IL-15'].
    IL-1b            has parents ['EOTAXIN', 'GM-CSF', 'FGF-2'].
    IL-7             has parents ['VEGF', 'Brinkman-Index', 'FGF-2'].
    IL-36β           has parents ['IL-10', 'IL-7', 'MCP-1'].
    IL-9             has parents ['IL-1b', 'IL-36β', 'MCP-1'].
    TGFB3            has parents ['FGF-2', 'IL-7', 'IFN-a2'].
    IL-17            has parents ['MIP-1b', 'smoking-status', 'IL-3'].
    Collagen-disease has parents ['MIP-1a', 'IL-5', 'IL-1a'].
    MCP-3            has parents ['MIP-1a', 'IL-5', 'IL-12P40'].
    IPAF             has parents ['smoking-status', 'TGFB3', 'MIP-1b'].
    TNFa             has parents ['EOTAXIN', 'MCP-3', 'GRO'].
    TGF-a            has parents ['IL-1b', 'TGFB3', 'EOTAXIN'].
    MMP-1            has parents ['MIP-1b', 'Brinkman-Index', 'GM-CSF'].
    BAL(neutro-%)    has parents ['TGFB3', 'TGF-a', '90day-mortality'].
    IL-1RA           has parents ['TGFB1', 'IL-9', 'FGF-2'].
    TGFB2            has parents ['IL-5', 'IL-1RA', 'TGFB1'].
    FRACTALKINE      has parents ['TGFB1', 'BAL(neutro-%)', 'IL-12P40'].
    sex              has parents ['MCP-3', 'TGFB2', 'IL-15'].
    MDC              has parents ['MIP-1a', 'TGF-a', 'FGF-2'].
    IFN-g            has parents ['IL-3', 'FRACTALKINE', 'TGFB1'].
    IL-12P70         has parents ['90day-mortality', 'TNFa', 'GRO'].
    IP-10            has parents ['IL-17', 'IPAF', 'IL-10'].
    IL-13            has parents ['IPAF', 'MDC', 'IL-12P40'].
    BAL(Eos-%)       has parents ['GM-CSF', 'IL-36β', 'IL-1a'].
    BAL(CD4/8)       has parents ['IFN-g', 'IL-13', 'IL-12P40'].
    sCD40L           has parents ['TGFB1', 'IL-36β', 'VEGF'].
    emphysema        has parents ['IL-1a', 'IL-12P70', 'MCP-1'].
    Flt-3L           has parents ['MIP-1b', 'IFN-g', 'GM-CSF'].
    IL-2             has parents ['FGF-2', 'IL-10', 'MCP-1'].
    P/F-ratio        has parents ['IP-10', 'Flt-3L', 'IPAF'].
    Baseline-ILD     has parents ['IL-17', 'IP-10', 'MIP-1b'].
    BAL(Lymph-%)     has parents ['MCP-3', 'IFN-g', 'IL-5'].
    BAL(M-%)         has parents ['IL-13', 'Baseline-ILD', 'FRACTALKINE'].
    G-CSF            has parents ['TGFB2', 'emphysema', 'smoking-status'].
    MMP-7            has parents ['IP-10', 'P/F-ratio', 'TGF-a'].
    TNFb             has parents ['BAL(neutro-%)', 'IL-12P70', 'TNFa'].
    age              has parents ['FRACTALKINE', 'BAL(CD4/8)', '90day-mortality'].
    CRP              has parents ['smoking-status', 'TGFB3', 'FGF-2'].
    LDH              has parents ['G-CSF', 'age', 'TGFB3'].
    IL-6             has parents ['BAL(CD4/8)', 'TNFb', 'MIP-1b'].
    EGF              has parents ['MDC', 'TNFb', 'IL-36β'].
    IL-4             has parents ['BAL(CD4/8)', 'MMP-7', 'TGFB2'].
    IL-8             has parents ['IL-10', 'TGF-a', 'FGF-2'].

In [19]:
# 合成データセットで生成される症例数。
num_tuples_to_generate = 5000

# 実際に模擬データを作成するコード
generator = DataGenerator()

# ベイズモデルの応用（模擬データの作成）
# description_fileとして定義してあるJSONファイルにベイズモデルが学習したカテゴリカルアトリビュートの特徴が保存される
# num_tuples_to_generateは生成される症例数
generator.generate_dataset_in_correlated_attribute_mode(num_tuples_to_generate, description_file)

# 作成した模擬データをsynthetic_dataとして定義したcsvファイルに保存する
generator.save_synthetic_data(synthetic_data)

# pandasのデータフレームとして模擬データを読み込む
synthetic_df = pd.read_csv(synthetic_data)
synthetic_df.head()

   ID  90day-mortality  sex   age  ...       TNFa  TNFb       VEGF    IL-36β
0   0              1.0  1.0  80.0  ...  48.756890   3.2  36.316894  4.221958
1   1              1.0  0.0  59.0  ...  30.680322   3.2  12.715458  2.000000
2   2              1.0  0.0  78.0  ...  18.979407   3.2  50.088339  2.297510
3   3              1.0  1.0  81.0  ...  43.692546   3.2  37.787405  2.000000
4   4              0.0  1.0  80.0  ...  44.787819   3.2  35.808766  4.221958

[5 rows x 63 columns]

In [20]:
# 新しく作成した模擬データは上記で作成したsynthetic_df内にあるため、AE_FILD_df_idfにデータを足す
AE_FILD_idf_syn = pd.concat([AE_FILD_df_idf, synthetic_df])

In [21]:
# # ベイズネットワークを作成するためにデータの要素をストリングに変換したため、上記で作成したディクショナリーを元に数字に変換する
# for columns in AE_FILD_idf_syn.columns:
#     for key,value in columnname_dict.items():
#       if columns == key:
#         for sub_k, sub_v in value.items():
#           AE_FILD_idf_syn[columns].replace({sub_k:value}, inplace=True)
# AE_FILD_idf_syn.head()

In [22]:
# ! pip install ydata_synthetic
# # 機械学習モデルがデータを学習する為に使うトランスフォメーション層の導入
# from ydata_synthetic.preprocessing import *

# train_data = AE_FILD_df.loc[AE_FILD_df['90day mortality survival:0 death:1']==1].copy()

# data = transformations(train_data)

# print("Dataset info: Number of records - {} Number of variables - {}".format(train_data.shape[0], train_data.shape[1]))

In [23]:
# from sklearn.neighbors import KernelDensity
# from sklearn.model_selection import GridSearchCV

# # ガウス法に基づきまずデータセットの密度をnumpyで表すためbandwithの設定
# # このbandwithの値に基づきデータ全体のパターンを機械学習モデルが予測しようとするため、機械学習モデルが勝手に最適bandwithを見つけてくれるものの、初期設定は重要
# bandwith_params = {'bandwidth': np.arange(0.01,1,0.05)} # [0.01 から１]の間でステップ0.05で値を作成
# # モデルをスキャンして最適パラメーターを見つける機械学習モデル（模擬データを作成するのに最適）
# grid_search = GridSearchCV(KernelDensity(), bandwith_params)
# # Aは従来の患者データ。fit()することで上記の機械学習モデルをトレーニングしてデータ内のパターンを学習してもらう
# grid_search.fit(A)
# kde = grid_search.best_estimator_

# # rand_stateの定義（rand_stateは新しいデータを作成する際のseedの定義）
# rand_state = 11
# # トレーニングしたモデルを使い新しい症例を20例作成してもらう
# new_data = kde.sample(20, random_state = rand_state)

# #　新しい症例を元のデータに加る
# A_updated = np.concatenate((A, new_data), axis=0)

In [24]:
# 今回の機械学習に使うライブラリーはsklearnのRF解析
# sklearnが機械学習モデルを適応できるようにデータをnumpyのarrayに変換する
A = AE_FILD_idf_syn.values #.valuesはnumpy arrayを出力する　
print(A)

[[5.58277000e+05 0.00000000e+00 0.00000000e+00 ... 3.20000000e+00
  3.20000000e+00 4.22195768e+00]
 [1.84882700e+06 0.00000000e+00 1.00000000e+00 ... 3.20000000e+00
  3.20000000e+00 2.00000000e+00]
 [1.90234900e+06 0.00000000e+00 0.00000000e+00 ... 3.20000000e+00
  3.20000000e+00 2.00000000e+00]
 ...
 [4.99700000e+03 1.00000000e+00 0.00000000e+00 ... 3.20000000e+00
  5.31855392e+01 2.00000000e+00]
 [4.99800000e+03 1.00000000e+00 0.00000000e+00 ... 3.20000000e+00
  1.83483758e+01 2.00000000e+00]
 [4.99900000e+03 1.00000000e+00 1.00000000e+00 ... 3.20000000e+00
  2.12554829e+01 2.00000000e+00]]

In [25]:
# 後で、乗算と除算ができるように、すべての値を浮動小数点に変換する
A = A.astype('float64')
print(A)

[[5.58277000e+05 0.00000000e+00 0.00000000e+00 ... 3.20000000e+00
  3.20000000e+00 4.22195768e+00]
 [1.84882700e+06 0.00000000e+00 1.00000000e+00 ... 3.20000000e+00
  3.20000000e+00 2.00000000e+00]
 [1.90234900e+06 0.00000000e+00 0.00000000e+00 ... 3.20000000e+00
  3.20000000e+00 2.00000000e+00]
 ...
 [4.99700000e+03 1.00000000e+00 0.00000000e+00 ... 3.20000000e+00
  5.31855392e+01 2.00000000e+00]
 [4.99800000e+03 1.00000000e+00 0.00000000e+00 ... 3.20000000e+00
  1.83483758e+01 2.00000000e+00]
 [4.99900000e+03 1.00000000e+00 1.00000000e+00 ... 3.20000000e+00
  2.12554829e+01 2.00000000e+00]]

In [26]:
# print(A_updated)
# print(A_updated.shape)

In [27]:
# 行数と列数を変数として保管する
NUM_ROWS, NUM_COLS = A.shape
print(f"\nこのデータセットの行数：{NUM_COLS}、列数：{NUM_ROWS}")

このデータセットの行数：63、列数：5060

In [28]:
# データセットのフィーチャー・ラベル定義

X_all = A[:,0:63].copy()  # X (フィーチャー) ... 全ての行
y_all = A[:,1].copy()    # y (ラベル) ... 全ての行, 2列目のみ

# Create a copy of X_all and y_all to apply rf analysis to later
X_all_rf = X_all.copy()
y_all_rf = y_all.copy()

print(f"X_all (フィーチャーのみ: 10行まで) \n {X_all[:10,:]}")
print(f"y_all (ラベルのみ) \n {y_all}")

X_all (フィーチャーのみ: 10行まで)
 [[5.58277000e+05 0.00000000e+00 0.00000000e+00 7.80000000e+01
  1.00000000e+00 1.60000000e+03 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 2.91666667e+02 3.45000000e+02
  2.35000000e+00 1.59900000e+03 4.10000000e+01 3.80000000e+01
  3.00000000e+00 1.30000000e+01 3.50000000e+00 6.64773204e+02
  1.33137916e+04 6.21768045e+01 4.04388091e+01 9.76562500e+00
  4.45038295e+00 6.24694689e+00 1.09631327e+01 3.20000000e+00
  1.08365991e+01 3.20000000e+00 3.20000000e+00 3.32659886e+01
  3.20000000e+00 3.20000000e+00 9.54746558e+02 3.20000000e+00
  3.47345075e+01 3.20000000e+00 8.15306905e+01 3.20000000e+00
  3.20000000e+00 3.20000000e+00 1.26679837e+01 3.20000000e+00
  3.95799401e+02 3.37974706e+00 3.20000000e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 1.44513353e+01 3.20000000e+00
  2.30161662e+01 3.20000000e+00 3.13439925e+02 2.16094095e+03
  1.00987865e+03 2.89063159e+01 3.09405765e+01 4.48326515e+00
  3.20000000e+00 3.20000000e+00 4.22195768e+00]
 [1.84882700e+06 0.00000000e+00 1.00000000e+00 7.20000000e+01
  0.00000000e+00 0.00000000e+00 0.00000000e+00 2.00000000e+00
  0.00000000e+00 0.00000000e+00 2.64571429e+02 2.77000000e+02
  5.65000000e+00 1.62000000e+03 1.80000000e+01 2.10000000e+01
  0.00000000e+00 6.10000000e+01 3.90000000e+00 5.61092206e+02
  1.21072533e+04 8.33563093e+01 6.44604732e+01 9.76562500e+00
  6.93255880e+00 6.24694689e+00 1.59634485e+01 3.20000000e+00
  5.30382982e+01 3.20000000e+00 4.63580561e+00 7.57335218e+01
  6.71073463e+00 1.08491713e+01 2.84970353e+03 9.80117950e+00
  4.61356020e+01 3.20000000e+00 6.00212600e+01 3.20000000e+00
  3.20000000e+00 3.20000000e+00 1.69253593e+01 3.20000000e+00
  1.14915176e+03 6.37370561e+00 3.20000000e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 2.66035850e+01 3.20000000e+00
  6.05126087e+01 3.20000000e+00 3.25398968e+02 1.56479402e+04
  1.94366385e+03 2.51051658e+01 2.53425913e+01 2.40742739e+01
  3.20000000e+00 3.20000000e+00 2.00000000e+00]
 [1.90234900e+06 0.00000000e+00 0.00000000e+00 8.60000000e+01
  0.00000000e+00 0.00000000e+00 0.00000000e+00 2.00000000e+00
  0.00000000e+00 0.00000000e+00 2.50000000e+02 2.69000000e+02
  6.50000000e+00 1.07300000e+03 2.00000000e+00 8.10000000e+01
  4.00000000e+00 1.20000000e+01 2.50000000e+00 5.79213448e+01
  6.61793760e+03 1.76362853e+01 1.67883461e+01 9.76562500e+00
  3.80253444e+00 6.24694689e+00 5.76794706e+00 3.20000000e+00
  3.28001631e+01 8.79158795e+00 3.20000000e+00 6.27652967e+01
  3.86735882e+00 3.20000000e+00 4.33780612e+02 3.20000000e+00
  4.01899560e+00 3.20000000e+00 1.40358150e+01 3.20000000e+00
  3.20000000e+00 3.20000000e+00 2.36762695e+01 3.20000000e+00
  6.70580797e+01 3.20000000e+00 3.20000000e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 1.22881748e+01 3.20000000e+00
  3.20000000e+00 3.20000000e+00 3.57239405e+01 2.80782648e+03
  2.43983235e+02 5.91213979e+00 2.36984667e+01 8.74870346e+00
  3.20000000e+00 3.20000000e+00 2.00000000e+00]
 [3.16553100e+06 0.00000000e+00 0.00000000e+00 5.80000000e+01
  1.00000000e+00 5.00000000e+02 0.00000000e+00 2.00000000e+00
  0.00000000e+00 0.00000000e+00 2.00000000e+02 5.38000000e+02
  1.12600000e+01 2.39200000e+03 1.30000000e+01 4.70000000e+01
  1.40000000e+01 2.50000000e+01 4.30000000e+00 2.92713992e+02
  8.25495669e+03 1.23918901e+01 4.07056756e+01 9.76562500e+00
  3.80253444e+00 6.24694689e+00 9.39852644e+00 3.20000000e+00
  2.00276409e+01 3.20000000e+00 3.20000000e+00 4.09284150e+01
  4.62571266e+00 3.20000000e+00 4.16843721e+02 3.20000000e+00
  2.14473484e+01 3.20000000e+00 3.67546548e+01 3.20000000e+00
  3.20000000e+00 3.20000000e+00 4.92580626e+00 3.20000000e+00
  2.05470611e+02 3.20000000e+00 3.20000000e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 1.11742939e+01 3.20000000e+00
  2.45173355e+01 3.20000000e+00 8.75063228e+01 3.90890038e+03
  6.37958551e+02 3.51869020e+00 1.48707141e+01 3.79289660e+00
  3.20000000e+00 3.20000000e+00 2.00000000e+00]
 [3.25368300e+06 0.00000000e+00 0.00000000e+00 7.60000000e+01
  1.00000000e+00 8.00000000e+02 0.00000000e+00 3.00000000e+00
  0.00000000e+00 0.00000000e+00 3.80952381e+02 3.72000000e+02
  6.43000000e+00 1.55500000e+03 9.00000000e+00 3.70000000e+01
  3.60000000e+01 7.00000000e+00 2.30000000e+00 6.45580358e+02
  2.71107196e+04 6.93445629e+01 9.29778795e+01 9.76562500e+00
  4.35006933e+00 6.24694689e+00 3.61324603e+01 3.99200606e+00
  1.99486543e+01 9.55410507e+00 3.20000000e+00 1.60465886e+01
  3.20000000e+00 3.20000000e+00 2.52724913e+02 3.85745212e+01
  4.06313089e+01 3.20000000e+00 9.46005892e+02 3.20000000e+00
  3.20000000e+00 3.20000000e+00 6.57253929e+00 3.20000000e+00
  1.08932145e+03 3.20000000e+00 3.20000000e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 7.74538749e+00 3.32750795e+01
  2.40737287e+02 3.20000000e+00 1.79661551e+02 2.57546732e+03
  3.49547492e+03 3.18217851e+01 1.00036875e+02 2.12332605e+01
  3.20000000e+00 3.20000000e+00 2.00000000e+00]
 [3.93289400e+06 0.00000000e+00 0.00000000e+00 8.10000000e+01
  0.00000000e+00 0.00000000e+00 0.00000000e+00 2.00000000e+00
  0.00000000e+00 0.00000000e+00 3.25000000e+02 3.43000000e+02
  4.20000000e-01 5.82000000e+03 2.00000000e+00 8.10000000e+01
  1.00000000e+00 1.50000000e+01 3.10000000e+00 4.62588105e+01
  9.60329684e+03 1.10800065e+01 2.33008940e+01 9.76562500e+00
  4.35006933e+00 6.24694689e+00 6.67147878e+00 3.20000000e+00
  3.28001631e+01 6.13752389e+00 3.20000000e+00 4.09284150e+01
  8.29413228e+00 3.20000000e+00 3.20197878e+02 3.20000000e+00
  1.56167148e+01 3.20000000e+00 2.29581430e+01 3.20000000e+00
  3.20000000e+00 3.20000000e+00 1.02043389e+01 3.20000000e+00
  5.18488947e+01 3.20000000e+00 3.20000000e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 6.52271903e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 2.70957836e+01 2.14361059e+03
  3.17600056e+02 1.08802641e+01 2.92194514e+01 4.59370782e+00
  3.20000000e+00 3.20000000e+00 2.00000000e+00]
 [4.38113400e+06 0.00000000e+00 0.00000000e+00 7.80000000e+01
  1.00000000e+00 1.00000000e+03 1.00000000e+00 2.00000000e+00
  0.00000000e+00 0.00000000e+00 3.33333333e+02 1.87000000e+02
  1.43100000e+01 3.58000000e+02 5.30000000e+01 1.30000000e+01
  5.00000000e+00 2.90000000e+01 3.80000000e+00 2.34392214e+02
  1.20867255e+04 2.02661750e+01 2.48422792e+01 9.76562500e+00
  4.85019574e+00 6.24694689e+00 4.28304635e+00 3.20000000e+00
  2.71388203e+01 3.61759147e+00 3.60020004e+00 6.64228241e+01
  6.42167825e+00 3.20000000e+00 4.35097287e+02 3.20000000e+00
  1.03869901e+01 3.20000000e+00 7.75214312e+01 3.20000000e+00
  3.79965391e+00 3.20000000e+00 4.92580626e+00 3.20000000e+00
  3.81310620e+02 1.00289179e+01 3.20000000e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 8.90290020e+00 3.20000000e+00
  1.29276818e+02 3.20000000e+00 1.77115594e+02 2.57808820e+03
  3.17652448e+02 1.21770157e+01 3.37823466e+01 4.21605041e+00
  3.20000000e+00 3.20000000e+00 2.00000000e+00]
 [4.55105200e+06 0.00000000e+00 1.00000000e+00 7.60000000e+01
  1.00000000e+00 1.00000000e+02 0.00000000e+00 3.00000000e+00
  1.00000000e+00 0.00000000e+00 2.85714286e+02 4.58000000e+02
  4.06000000e+00 9.81000000e+02 4.00000000e+00 7.60000000e+01
  0.00000000e+00 2.00000000e+01 1.20000000e+00 5.19764636e+01
  3.06002225e+03 9.76562500e+00 1.05305820e+01 9.76562500e+00
  4.61020142e+00 6.24694689e+00 1.46281446e+01 3.20000000e+00
  3.56517121e+01 3.20000000e+00 3.20000000e+00 5.95919839e+01
  9.53838363e+00 3.46456693e+00 6.45003503e+02 3.53967745e+00
  4.94520648e+01 3.20000000e+00 1.19839069e+01 3.20000000e+00
  3.86539075e+00 3.20000000e+00 6.01835112e+00 3.20000000e+00
  1.54113188e+02 3.20000000e+00 3.20000000e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 1.33697551e+01 3.20000000e+00
  2.84733662e+01 3.20000000e+00 5.06471351e+01 1.24546228e+04
  1.81096965e+03 1.98126786e+01 5.37736706e+01 7.91239819e+00
  3.20000000e+00 3.20000000e+00 2.00000000e+00]
 [4.62202600e+06 0.00000000e+00 0.00000000e+00 7.40000000e+01
  1.00000000e+00 6.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 3.33333333e+02 3.29000000e+02
  3.20000000e-01 1.80700000e+03 9.00000000e+00 3.60000000e+01
  6.00000000e+00 4.80000000e+01 2.30000000e+00 1.96216305e+02
  1.68360205e+04 3.43433219e+01 2.81528146e+01 9.76562500e+00
  3.51513163e+00 6.24694689e+00 3.20000000e+00 3.20000000e+00
  2.41137743e+01 3.20000000e+00 3.92282446e+00 1.51040699e+02
  3.01332476e+01 3.20000000e+00 4.79438941e+02 3.20000000e+00
  8.59088430e+01 3.20000000e+00 6.18347700e+01 3.20000000e+00
  1.24521664e+01 3.20000000e+00 4.35081617e+00 3.20000000e+00
  5.46012758e+02 8.40043329e+00 3.20000000e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 7.74538749e+00 3.20000000e+00
  6.16337504e+00 3.20000000e+00 7.88088091e+01 1.75437189e+03
  3.31854573e+03 1.19226732e+01 1.04047071e+01 3.20000000e+00
  3.20000000e+00 3.20000000e+00 2.00000000e+00]
 [4.62452700e+06 1.00000000e+00 0.00000000e+00 8.10000000e+01
  1.00000000e+00 2.00000000e+02 0.00000000e+00 2.00000000e+00
  0.00000000e+00 0.00000000e+00 1.15000000e+02 1.97000000e+02
  6.20000000e+00 5.27000000e+02 7.80000000e+01 1.00000000e+01
  0.00000000e+00 1.20000000e+01 1.10000000e+00 7.62947062e+02
  6.52613857e+03 4.69353749e+01 9.03684261e+01 9.76562500e+00
  4.35006933e+00 6.24694689e+00 8.63348582e+00 3.20000000e+00
  2.80221948e+01 3.20000000e+00 3.67601155e+00 5.82416936e+01
  5.48026833e+00 3.20000000e+00 6.04823231e+02 3.20000000e+00
  2.69024532e+01 3.20000000e+00 4.36173380e+01 3.20000000e+00
  3.20000000e+00 3.20000000e+00 3.77582608e+00 3.20000000e+00
  2.62225993e+02 3.20000000e+00 3.20000000e+00 3.20000000e+00
  3.20000000e+00 3.20000000e+00 4.39572319e+00 3.20000000e+00
  2.69628169e+01 3.20000000e+00 8.29118010e+01 1.96715537e+03
  7.25591981e+02 3.20000000e+00 4.97833747e+00 3.79289660e+00
  3.20000000e+00 3.20000000e+00 2.00000000e+00]]
y_all (ラベルのみ)
 [0. 0. 0. ... 1. 1. 1.]

In [29]:
# フィーチャーの重要性を表すpythonのディクショナリー
# 最初の値は全ての行に1（データの内容を変えないように１で掛け算してもデータは変わらない）で指定しておけば、RFモデルがトレーニングする際に自動で更新してくれる
COL_WEIGHT_DICT = {}

for colname in AE_FILD_df_idf.columns[1:]: # 最初の行が出力データを表すため、フィーチャーの重みは最初の行以外を考慮する
  i = AE_FILD_df_idf.columns.get_loc(colname)
  weight = 1
  COL_WEIGHT_DICT[colname] = 1
  print(f"行名{colname}の重みを{weight}に指定しました")
  X_all[:,i] *= weight # そのコラム内のデータをweightで掛け算する

行名90day-mortalityの重みを1に指定しました
行名sexの重みを1に指定しました
行名ageの重みを1に指定しました
行名smoking-statusの重みを1に指定しました
行名Brinkman-Indexの重みを1に指定しました
行名emphysemaの重みを1に指定しました
行名Baseline-ILDの重みを1に指定しました
行名Collagen-diseaseの重みを1に指定しました
行名IPAFの重みを1に指定しました
行名P/F-ratioの重みを1に指定しました
行名LDHの重みを1に指定しました
行名CRPの重みを1に指定しました
行名KL-6の重みを1に指定しました
行名BAL(neutro-%)の重みを1に指定しました
行名BAL(Lymph-%)の重みを1に指定しました
行名BAL(Eos-%)の重みを1に指定しました
行名BAL(M-%)の重みを1に指定しました
行名BAL(CD4/8)の重みを1に指定しました
行名MMP-1の重みを1に指定しました
行名MMP-7の重みを1に指定しました
行名TGFB1の重みを1に指定しました
行名TGFB2の重みを1に指定しました
行名TGFB3の重みを1に指定しました
行名EGFの重みを1に指定しました
行名FGF-2の重みを1に指定しました
行名EOTAXINの重みを1に指定しました
行名TGF-aの重みを1に指定しました
行名G-CSFの重みを1に指定しました
行名Flt-3Lの重みを1に指定しました
行名GM-CSFの重みを1に指定しました
行名FRACTALKINEの重みを1に指定しました
行名IFN-a2の重みを1に指定しました
行名IFN-gの重みを1に指定しました
行名GROの重みを1に指定しました
行名IL-10の重みを1に指定しました
行名MCP-3の重みを1に指定しました
行名IL-12P40の重みを1に指定しました
行名MDCの重みを1に指定しました
行名IL-12P70の重みを1に指定しました
行名IL-13の重みを1に指定しました
行名IL-15の重みを1に指定しました
行名sCD40Lの重みを1に指定しました
行名IL-17の重みを1に指定しました
行名IL-1RAの重みを1に指定しました
行名IL-1aの重みを1に指定しました
行名IL-9の重みを1に指定しました
行名IL-1bの重みを1に指定しました
行名IL-2の重みを1に指定しました
行名IL-3の重みを1に指定しました
行名IL-4の重みを1に指定しました
行名IL-5の重みを1に指定しました
行名IL-6の重みを1に指定しました
行名IL-7の重みを1に指定しました
行名IL-8の重みを1に指定しました
行名IP-10の重みを1に指定しました
行名MCP-1の重みを1に指定しました
行名MIP-1aの重みを1に指定しました
行名MIP-1bの重みを1に指定しました
行名TNFaの重みを1に指定しました
行名TNFbの重みを1に指定しました
行名VEGFの重みを1に指定しました
行名IL-36βの重みを1に指定しました

In [30]:
# トレーニングデータとテストデータに入力データを分ける
# トレーニングデータ内のどのデータをどちらのデータセットに振り分けるかの指定をnpのrandom.permutationにより、毎回機械学習を行う際にランダムで決めてもらう
indices = np.random.permutation(len(y_all)) # ラベルの行のindexを記憶している変数
print(f"indices: {indices}")

# X_allとy_allに上記でnpが主力したランダムindexでデータセットの内容をシャッフルする （注：X_allとy_allは必ず同じindexでシャッフルしなくてはいけない）
X_all = X_all[indices]
y_all = y_all[indices]

print("置き換わったフィーチャーリスト：\n", X_all[:10,:])
print("置き換わったラベルリスト：\n", y_all)

indices: [4254 3114 3912 ... 2375 4455 2951]
置き換わったフィーチャーリスト：
 [[4.19400000e+03 0.00000000e+00 0.00000000e+00 8.40000000e+01
  2.00000000e+00 9.00000000e+02 1.00000000e+00 1.00000000e+00
  1.00000000e+00 0.00000000e+00 3.87527182e+02 3.80200000e+03
  2.54438684e+01 4.19400000e+03 7.20000000e+01 3.20000000e+01
  4.00000000e+00 7.50000000e+01 7.02506069e+00 4.69834036e+02
  4.28264607e+04 8.28264825e+01 2.95251496e+01 1.19444864e+01
  1.11662842e+01 5.80550897e+00 5.50304130e+01 3.20000000e+00
  2.28803529e+01 6.64031158e+00 7.80072834e+00 9.34425582e+01
  1.84379778e+01 2.42276698e+01 2.44060697e+03 1.13421331e+01
  1.12622484e+02 3.42687110e+00 4.90373208e+02 3.20000000e+00
  1.12612804e+01 3.50041271e+00 2.25295347e+01 3.20000000e+00
  1.22134764e+03 2.04905431e+01 3.20000000e+00 1.23180752e+01
  3.20000000e+00 3.20000000e+00 2.60874318e+01 2.46905390e+01
  9.58270984e+01 5.23618062e+00 1.32136244e+03 2.05369547e+03
  4.22991567e+03 6.91956841e+01 6.70273168e+01 3.96602277e+01
  3.20000000e+00 1.06237223e+01 2.29750983e+00]
 [3.05400000e+03 0.00000000e+00 1.00000000e+00 8.30000000e+01
  2.00000000e+00 4.80000000e+02 0.00000000e+00 2.00000000e+00
  0.00000000e+00 0.00000000e+00 3.30411840e+02 9.39000000e+02
  1.88939677e+01 3.05400000e+03 1.60000000e+01 7.70000000e+01
  1.10000000e+01 2.10000000e+01 4.07577333e-01 3.72305437e+03
  7.03409360e+04 9.31587774e+01 1.58024878e+02 1.92998940e+01
  6.74273725e+00 1.15287038e+01 8.43003350e+01 3.20000000e+00
  5.55944451e+01 3.46270181e+00 8.34317880e+00 1.07519186e+02
  1.01078666e+01 1.42443045e+01 1.77881696e+03 3.14714844e+01
  1.18408330e+02 3.40983482e+00 8.14817536e+02 3.20000000e+00
  8.01924725e+00 3.23024551e+00 1.41636471e+01 3.20000000e+00
  1.20766697e+03 3.12243913e+01 3.20000000e+00 9.28305098e+00
  3.20000000e+00 3.20000000e+00 8.59984385e+00 3.01832816e+01
  3.98604458e+02 3.75166887e+00 6.14805702e+02 2.49374396e+03
  4.46484477e+03 8.71106125e+01 4.37033573e+02 4.57286208e+01
  3.20000000e+00 1.93895188e+01 2.00000000e+00]
 [3.85200000e+03 0.00000000e+00 1.00000000e+00 6.60000000e+01
  1.00000000e+00 1.75000000e+03 1.00000000e+00 2.00000000e+00
  0.00000000e+00 0.00000000e+00 1.58370825e+02 1.37700000e+03
  1.08073175e+01 3.85200000e+03 2.90000000e+01 9.00000000e+00
  1.90000000e+01 9.00000000e+00 7.19437953e+00 9.63602630e+02
  1.97304469e+04 1.32129045e+02 7.50932045e+01 1.76695822e+01
  4.29425366e+00 6.23954321e+00 1.25760137e+01 3.20000000e+00
  2.01227425e+02 6.19208099e+00 5.24207452e+00 7.49473123e+01
  1.30688701e+01 1.22672357e+01 6.81211867e+02 9.55775224e+00
  1.42922204e+02 3.46388420e+00 2.77527510e+02 3.20000000e+00
  6.36767099e+00 3.86041739e+00 1.04124296e+01 3.20000000e+00
  1.44796064e+03 4.99257243e+01 3.20000000e+00 1.40485272e+01
  3.20000000e+00 3.20000000e+00 1.48809626e+01 3.46309857e+00
  1.49468272e+01 6.45230730e+00 1.41214205e+03 1.72636002e+04
  2.90069992e+03 1.40293092e+01 4.15568377e+01 2.22202941e+01
  3.20000000e+00 3.77540091e+01 4.22195768e+00]
 [2.97500000e+03 1.00000000e+00 1.00000000e+00 6.70000000e+01
  1.00000000e+00 2.40000000e+03 0.00000000e+00 1.00000000e+00
  0.00000000e+00 1.00000000e+00 4.43572253e+02 1.63100000e+03
  1.53536327e+01 2.97500000e+03 2.90000000e+01 1.10000000e+01
  3.30000000e+01 8.90000000e+01 6.79748989e+00 3.82868942e+03
  2.70976106e+04 9.41133200e+01 1.40740027e+02 1.57025264e+01
  6.23649189e+00 1.27044727e+01 5.13222298e+01 3.99200606e+00
  3.50018268e+02 4.17252147e+00 4.93129345e+00 1.10994248e+02
  1.96682741e+01 1.13429513e+01 2.75975479e+03 1.35191101e+01
  4.08099738e+01 4.20779892e+00 8.26452192e+02 3.20000000e+00
  4.71131257e+00 4.21642674e+00 8.75162308e+00 3.20000000e+00
  1.28256406e+03 1.98908119e+01 3.20000000e+00 1.16981405e+01
  3.20000000e+00 3.20000000e+00 1.32995559e+01 3.09101083e+01
  4.62380476e+02 6.89374492e+00 5.06563577e+02 1.31619943e+04
  1.48179745e+03 8.00286944e+00 5.41894726e+02 5.26840551e+01
  3.20000000e+00 5.84303237e+01 4.22195768e+00]
 [3.33900000e+03 1.00000000e+00 0.00000000e+00 6.30000000e+01
  0.00000000e+00 1.60000000e+03 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 2.03760985e+02 3.31900000e+03
  1.13765230e+01 3.33900000e+03 4.00000000e+01 2.30000000e+01
  1.00000000e+01 5.60000000e+01 9.70741036e+00 7.75050102e+02
  6.09446298e+04 3.20084625e+01 1.82334761e+01 1.56004367e+01
  1.05824463e+01 4.66044190e+00 8.53642144e+01 3.20000000e+00
  2.76058815e+01 6.81661863e+00 7.40423314e+00 1.32194927e+02
  2.24685150e+01 1.37946905e+01 3.29758718e+02 3.56422240e+01
  9.06331001e+01 3.76844384e+00 3.28969582e+02 3.20000000e+00
  9.44029074e+00 3.38511138e+00 1.69296121e+01 3.20000000e+00
  3.48658604e+02 4.19021229e+01 3.20000000e+00 1.74296012e+01
  3.20000000e+00 3.20000000e+00 1.69905179e+01 2.93265859e+01
  3.34963485e+02 5.61996680e+00 7.96582964e+02 1.19829280e+04
  4.63579006e+02 5.54881471e+00 3.87755672e+02 3.42752405e+01
  3.20000000e+00 4.57654151e+00 2.00000000e+00]
 [1.85300000e+03 0.00000000e+00 0.00000000e+00 7.00000000e+01
  0.00000000e+00 1.98000000e+03 0.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 4.82097235e+02 5.88000000e+02
  7.47544081e+00 1.85300000e+03 1.30000000e+01 6.60000000e+01
  4.00000000e+00 8.70000000e+01 7.34601857e+00 1.19830168e+03
  5.57771852e+04 1.02274693e+02 1.73258121e+02 1.01790826e+01
  1.28348735e+01 1.55547690e+01 4.62271527e+01 3.20000000e+00
  3.70243755e+02 6.15136659e+00 6.99814446e+00 9.33483219e+01
  1.25732845e+01 9.43894044e+00 1.99178489e+03 8.14549934e+00
  3.62859071e+01 3.43552234e+00 2.71781721e+01 3.20000000e+00
  3.48481200e+00 3.27372254e+00 6.52180966e+00 3.20000000e+00
  1.72643366e+03 1.83529417e+01 3.20000000e+00 1.19925271e+01
  3.20000000e+00 3.20000000e+00 1.62755587e+01 3.35201020e+00
  4.04325355e+02 3.94080809e+00 8.74866640e+02 7.60942496e+03
  2.41232109e+03 2.65628616e+01 3.69492262e+02 5.36304571e+01
  3.20000000e+00 1.16547229e+01 2.29750983e+00]
 [4.91200000e+03 1.00000000e+00 1.00000000e+00 6.80000000e+01
  2.00000000e+00 6.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00 1.23343908e+02 9.43000000e+02
  8.63062280e+00 4.91200000e+03 3.90000000e+01 1.00000000e+01
  3.10000000e+01 5.10000000e+01 1.77047740e-01 2.78361026e+03
  5.54546122e+04 1.04569742e+02 4.23499698e+01 1.67951869e+01
  4.69289258e+00 1.07212345e+01 4.51756617e+01 3.99200606e+00
  1.53236862e+02 6.91085613e+00 4.88743317e+00 1.10384010e+02
  2.73315848e+01 1.87583108e+01 1.30139449e+03 1.30783633e+01
  1.69342903e+01 4.16262004e+00 7.53522631e+02 3.20000000e+00
  1.20874024e+01 4.15653749e+00 1.92754137e+01 3.20000000e+00
  1.21146392e+03 1.98576440e+01 3.20000000e+00 1.77411649e+01
  3.20000000e+00 3.20000000e+00 4.49509105e+00 1.11758855e+01
  1.41430007e+02 6.64626996e+00 1.06441264e+03 5.89722353e+03
  1.67386304e+03 2.37414457e+01 5.55942963e+02 4.90221703e+01
  3.20000000e+00 1.73401885e+01 2.00000000e+00]
 [4.92600000e+03 1.00000000e+00 0.00000000e+00 6.20000000e+01
  1.00000000e+00 1.00000000e+03 1.00000000e+00 1.00000000e+00
  1.00000000e+00 0.00000000e+00 1.52030821e+02 3.94800000e+03
  1.35139449e+01 4.92600000e+03 3.40000000e+01 6.10000000e+01
  2.70000000e+01 2.60000000e+01 2.83504391e-01 4.95974921e+02
  4.41884082e+03 1.16783809e+02 1.49560439e+02 1.90206173e+01
  1.17320419e+01 4.97677452e+00 6.69516509e+01 3.20000000e+00
  1.51196358e+02 4.35185270e+00 4.00357002e+00 2.25539170e+01
  1.30615337e+01 1.27187746e+01 1.52084990e+03 2.59376393e+01
  1.17346566e+02 3.65737290e+00 4.93597609e+01 3.20000000e+00
  7.95953563e+00 3.23829817e+00 1.21193293e+01 3.20000000e+00
  1.50907124e+03 3.15806528e+01 3.20000000e+00 1.36164925e+01
  3.20000000e+00 3.20000000e+00 1.48669614e+01 2.30793588e+01
  4.75395084e+02 7.47741462e+00 1.09402144e+03 1.36490909e+04
  3.95905527e+03 3.98153948e+01 9.43468783e+01 4.41119175e+00
  3.20000000e+00 2.99727978e+01 2.29750983e+00]
 [1.37000000e+03 1.00000000e+00 1.00000000e+00 7.00000000e+01
  2.00000000e+00 2.00000000e+02 1.00000000e+00 3.00000000e+00
  1.00000000e+00 0.00000000e+00 2.38887853e+02 1.68600000e+03
  6.29911124e+00 1.37000000e+03 1.60000000e+01 3.50000000e+01
  0.00000000e+00 8.80000000e+01 4.36777064e+00 3.55699384e+03
  3.24424886e+04 6.34406978e+01 1.00390783e+02 1.38916444e+01
  1.29360124e+01 3.91666731e+00 5.78036856e+01 3.20000000e+00
  2.32531384e+02 7.39165028e+00 4.69588589e+00 2.87255880e+01
  2.42723594e+01 2.14008745e+01 1.23421504e+03 3.49864825e+01
  3.89568961e+01 4.40982839e+00 8.52575127e+02 3.20000000e+00
  5.65287704e+00 3.25753261e+00 1.53102195e+01 3.20000000e+00
  1.21590588e+02 5.18897799e+01 3.20000000e+00 2.74117644e+01
  3.20000000e+00 3.20000000e+00 2.99187719e+01 5.10126728e+00
  6.38228766e+02 3.94140226e+00 1.11934781e+03 1.74185139e+04
  3.16606941e+03 1.64725857e+02 1.72008997e+02 1.51300462e+01
  3.20000000e+00 3.96594637e+00 4.22195768e+00]
 [5.06000000e+02 1.00000000e+00 0.00000000e+00 6.50000000e+01
  0.00000000e+00 6.00000000e+00 1.00000000e+00 2.00000000e+00
  0.00000000e+00 1.00000000e+00 4.58223011e+02 3.98400000e+03
  1.61935753e+01 5.06000000e+02 6.10000000e+01 6.80000000e+01
  4.00000000e+00 2.10000000e+01 9.52438579e-01 1.15296838e+03
  5.72943369e+04 8.13522751e+01 9.55337103e+01 1.56417677e+01
  1.16965176e+01 1.38626641e+01 2.38683130e+01 3.99200606e+00
  4.54211946e+01 6.93739822e+00 4.26083970e+00 3.65490258e+01
  2.46587151e+01 2.34718864e+01 2.82000766e+03 5.19586758e+00
  9.37207658e+01 4.19304001e+00 5.30805016e+02 3.20000000e+00
  1.22285381e+01 4.30447942e+00 1.42918677e+01 3.20000000e+00
  1.35082319e+03 2.10717051e+01 3.20000000e+00 3.96892728e+00
  3.20000000e+00 3.20000000e+00 5.97431134e+00 1.14292159e+01
  3.17234079e+02 6.78713014e+00 1.38594050e+03 9.02092462e+03
  5.02968103e+03 6.81319768e+01 1.56065325e+02 3.48085992e+01
  3.20000000e+00 1.65271980e+01 2.00000000e+00]]
置き換わったラベルリスト：
 [0. 0. 0. ... 1. 0. 1.]

In [31]:
# トレニーングデータとテストデータの振り分け
# 割合：トレーニング（8割）・テスト（2割）
NUM_ROWS = X_all.shape[0] # 列数
TEST_PERCENT = 0.2 # TEST ＋ TRAINING は必ず1にならなければいけない
TEST_SIZE = int(TEST_PERCENT * NUM_ROWS) 

X_test = X_all[:TEST_SIZE] # 0からTEST＿SIZEまでのデータ
y_test = y_all[:TEST_SIZE]

X_train = X_all[TEST_SIZE:] # TEST_SIZE以降のデータ
y_train = y_all[TEST_SIZE:]

print(f"トレーニング列数：{len(y_train)}、テスト列数：{len(y_test)}")

トレーニング列数：4048、テスト列数：1012

In [32]:
# RF解析に使うsklearnのライブラリーの導入
from sklearn import tree # 決定木モデル
from sklearn import ensemble # RF解析用のモデル
from sklearn.model_selection import cross_val_score # RF解析の最適解層をcross validationを使い見つけるためのモデル

In [33]:
# モデルの構築・モデルのトレーニング
# RF モデルの構築
# cross_valを使い、最適層を決めるんですが、事前に何階層を使えばいいかわからないため、適当に6階層決定木42と指定する
best_depth = 6
best_num_trees = 42
rforest_model = ensemble.RandomForestClassifier(max_depth=best_depth, n_estimators=best_num_trees) # ensemble.RandomForestClassifierからRF解析モデルを引っ張ってくる

# モデルの初期トレーニング
rforest_model.fit(X_train, y_train) # .fit()がトレーニングデータを使い、モデルをトレーニングしろというコマンド
print(f"RFモデルを{best_depth}層と{best_num_trees}決定木で作成しました")

RFモデルを6層と42決定木で作成しました

In [34]:
# 初期トレーニング後のモデルのパフォーマンス検証
# テストデータにrforest_modelに.predict()関数を応用し、RFモデルがラベルを何個正確に予測出来たかを検証する
predicted_labels = rforest_model.predict(X_test)
actual_labels = y_test

# ラベルをプリントして実際に予測vs.実際のラベルを見てみる
print(f"予測ラベル：{predicted_labels}")
print(f"実際ラベル: {actual_labels}")

# 正確性の出力
num_correct = sum(predicted_labels == actual_labels)
total = len(actual_labels)
print(f"正確性は：{num_correct/total * 100}％でした")

予測ラベル：[0. 0. 0. ... 1. 1. 0.]
実際ラベル: [0. 0. 0. ... 1. 1. 0.]
正確性は：99.90118577075098％でした

In [35]:
# cross validationを使い、階層や決定木の数をチューニングしてみる（ハイパーパラメーター）
# 注：過適合/過剰適合のバランスを見極めながらハイパーパラメーターチューニングを行う
best_accuracy = 0
best_depth = 1
best_num_trees = 42

for ntrees in range(50,450,100):  # 決定木50から350の間（ステップ数：100)
    for d in range(1,20): # 階層1から20の間
        rforest_model = ensemble.RandomForestClassifier(max_depth=d, 
                                                        n_estimators=ntrees)
        cv_scores = cross_val_score( rforest_model, X_train, y_train, cv=5 ) # 5 はトレーニング・テストの割合が8割・2割ということを表す
        average_cv_accuracy = cv_scores.mean()  # cvスコアの平均値cv=5はスコアを五つ出すため、その平均値を見る
        if average_cv_accuracy >= best_accuracy: # cvスコアの平均値正確性が現在の最適正確性を上回った場合、現在のcvスコア平均値を出した決定木数・階層を最適とする
            best_accuracy = average_cv_accuracy
            best_depth = d
            best_num_trees = ntrees
        print(f"階層: {d:2d} 決定木: {ntrees:3d} cv スコア平均値: {average_cv_accuracy:7.4f}")

print()
print(f"最適層: {best_depth}, 最適決定木数： {best_num_trees}, 最高予測精度：{best_accuracy}")

階層:  1 決定木:  50 cv スコア平均値:  0.6932
階層:  2 決定木:  50 cv スコア平均値:  0.9988
階層:  3 決定木:  50 cv スコア平均値:  0.9840
階層:  4 決定木:  50 cv スコア平均値:  0.9995
階層:  5 決定木:  50 cv スコア平均値:  0.9990
階層:  6 決定木:  50 cv スコア平均値:  0.9993
階層:  7 決定木:  50 cv スコア平均値:  0.9990
階層:  8 決定木:  50 cv スコア平均値:  0.9993
階層:  9 決定木:  50 cv スコア平均値:  0.9990
階層: 10 決定木:  50 cv スコア平均値:  0.9993
階層: 11 決定木:  50 cv スコア平均値:  0.9993
階層: 12 決定木:  50 cv スコア平均値:  0.9993
階層: 13 決定木:  50 cv スコア平均値:  0.9990
階層: 14 決定木:  50 cv スコア平均値:  0.9990
階層: 15 決定木:  50 cv スコア平均値:  0.9990
階層: 16 決定木:  50 cv スコア平均値:  0.9995
階層: 17 決定木:  50 cv スコア平均値:  0.9990
階層: 18 決定木:  50 cv スコア平均値:  0.9990
階層: 19 決定木:  50 cv スコア平均値:  0.9993
階層:  1 決定木: 150 cv スコア平均値:  0.6107
階層:  2 決定木: 150 cv スコア平均値:  0.9815
階層:  3 決定木: 150 cv スコア平均値:  0.9993
階層:  4 決定木: 150 cv スコア平均値:  0.9993
階層:  5 決定木: 150 cv スコア平均値:  0.9990
階層:  6 決定木: 150 cv スコア平均値:  0.9993
階層:  7 決定木: 150 cv スコア平均値:  0.9990
階層:  8 決定木: 150 cv スコア平均値:  0.9995
階層:  9 決定木: 150 cv スコア平均値:  0.9990
階層: 10 決定木: 150 cv スコア平均値:  0.9993
階層: 11 決定木: 150 cv スコア平均値:  0.9993
階層: 12 決定木: 150 cv スコア平均値:  0.9998
階層: 13 決定木: 150 cv スコア平均値:  0.9993
階層: 14 決定木: 150 cv スコア平均値:  0.9990
階層: 15 決定木: 150 cv スコア平均値:  0.9990
階層: 16 決定木: 150 cv スコア平均値:  0.9993
階層: 17 決定木: 150 cv スコア平均値:  0.9998
階層: 18 決定木: 150 cv スコア平均値:  0.9993
階層: 19 決定木: 150 cv スコア平均値:  0.9990
階層:  1 決定木: 250 cv スコア平均値:  0.6042
階層:  2 決定木: 250 cv スコア平均値:  0.9565
階層:  3 決定木: 250 cv スコア平均値:  0.9990
階層:  4 決定木: 250 cv スコア平均値:  0.9993
階層:  5 決定木: 250 cv スコア平均値:  0.9993
階層:  6 決定木: 250 cv スコア平均値:  0.9993
階層:  7 決定木: 250 cv スコア平均値:  0.9993
階層:  8 決定木: 250 cv スコア平均値:  0.9993
階層:  9 決定木: 250 cv スコア平均値:  0.9990
階層: 10 決定木: 250 cv スコア平均値:  0.9993
階層: 11 決定木: 250 cv スコア平均値:  0.9993
階層: 12 決定木: 250 cv スコア平均値:  0.9990
階層: 13 決定木: 250 cv スコア平均値:  0.9993
階層: 14 決定木: 250 cv スコア平均値:  0.9993
階層: 15 決定木: 250 cv スコア平均値:  0.9993
階層: 16 決定木: 250 cv スコア平均値:  0.9990
階層: 17 決定木: 250 cv スコア平均値:  0.9993
階層: 18 決定木: 250 cv スコア平均値:  0.9993
階層: 19 決定木: 250 cv スコア平均値:  0.9993
階層:  1 決定木: 350 cv スコア平均値:  0.6045
階層:  2 決定木: 350 cv スコア平均値:  0.9639
階層:  3 決定木: 350 cv スコア平均値:  0.9985
階層:  4 決定木: 350 cv スコア平均値:  0.9993
階層:  5 決定木: 350 cv スコア平均値:  0.9990
階層:  6 決定木: 350 cv スコア平均値:  0.9993
階層:  7 決定木: 350 cv スコア平均値:  0.9993
階層:  8 決定木: 350 cv スコア平均値:  0.9993
階層:  9 決定木: 350 cv スコア平均値:  0.9993
階層: 10 決定木: 350 cv スコア平均値:  0.9990
階層: 11 決定木: 350 cv スコア平均値:  0.9990
階層: 12 決定木: 350 cv スコア平均値:  0.9993
階層: 13 決定木: 350 cv スコア平均値:  0.9990
階層: 14 決定木: 350 cv スコア平均値:  0.9993
階層: 15 決定木: 350 cv スコア平均値:  0.9993
階層: 16 決定木: 350 cv スコア平均値:  0.9990
階層: 17 決定木: 350 cv スコア平均値:  0.9993
階層: 18 決定木: 350 cv スコア平均値:  0.9990
階層: 19 決定木: 350 cv スコア平均値:  0.9993

最適層: 17, 最適決定木数： 150, 最高予測精度：0.999753086419753

In [36]:
# 上記で見つけた最適層・最適決定木数をもとにモデルの構築・モデルのトレーニング
rforest_model = ensemble.RandomForestClassifier(max_depth=best_depth, n_estimators=best_num_trees) # ensemble.RandomForestClassifierからRF解析モデルを引っ張ってくる

# モデルを再度トレーニングする
rforest_model.fit(X_train, y_train) # .fit()がトレーニングデータを使い、モデルをトレーニングしろというコマンド
print(f"RFモデルを{best_depth}層と{best_num_trees}決定木で作成しました")

RFモデルを17層と150決定木で作成しました

In [37]:
#  ラベル毎に予測ラベルが実際のラベルと一致してるか確認する関数
def compare_labels(predicted_labels, actual_labels):
    NUM_LABELS = len(predicted_labels)
    num_correct = 0
    
    for i in range(NUM_LABELS): 
        p = int(round(predicted_labels[i]))         # round protects from fp error 
        a = int(round(actual_labels[i]))
        result = "incorrect"
        if p == a:  # if they match,
            result = ""       # no longer incorrect
            num_correct += 1  # and we count a match!

        print(f"row {i:>3d} : {p} {a}   {result}") 

    print(f"\n正確性は：{num_correct/NUM_LABELS * 100}％でした")
    return num_correct

In [38]:
# 再度トレーニングした後のモデルのパフォーマンス検証
# テストデータにrforest_modelに.predict()関数を応用し、RFモデルがラベルを何個正確に予測出来たかを検証する
predicted_labels = rforest_model.predict(X_test)
actual_labels = y_test

# ラベルをプリントして実際に予測vs.実際のラベルを見てみる
print(f"予測ラベル：{predicted_labels}")
print(f"実際ラベル: {actual_labels}")

# 正確性の出力
compare_labels(predicted_labels, actual_labels)

予測ラベル：[0. 0. 0. ... 1. 1. 0.]
実際ラベル: [0. 0. 0. ... 1. 1. 0.]
row   0 : 0 0
row   1 : 0 0
row   2 : 0 0
row   3 : 1 1
row   4 : 1 1
row   5 : 0 0
row   6 : 1 1
row   7 : 1 1
row   8 : 1 1
row   9 : 1 1
row  10 : 0 0
row  11 : 0 0
row  12 : 1 1
row  13 : 1 1
row  14 : 1 1
row  15 : 1 1
row  16 : 0 0
row  17 : 1 1
row  18 : 1 1
row  19 : 1 1
row  20 : 0 0
row  21 : 0 0
row  22 : 0 0
row  23 : 1 1
row  24 : 1 1
row  25 : 1 1
row  26 : 0 0
row  27 : 1 1
row  28 : 0 0
row  29 : 1 1
row  30 : 1 1
row  31 : 1 1
row  32 : 1 1
row  33 : 0 0
row  34 : 1 1
row  35 : 1 1
row  36 : 1 1
row  37 : 1 1
row  38 : 0 0
row  39 : 1 1
row  40 : 1 1
row  41 : 1 1
row  42 : 1 1
row  43 : 0 0
row  44 : 0 0
row  45 : 1 1
row  46 : 1 1
row  47 : 1 1
row  48 : 0 0
row  49 : 0 0
row  50 : 1 1
row  51 : 1 1
row  52 : 0 0
row  53 : 0 0
row  54 : 1 1
row  55 : 0 0
row  56 : 0 0
row  57 : 1 1
row  58 : 0 0
row  59 : 0 0
row  60 : 0 0
row  61 : 1 1
row  62 : 0 0
row  63 : 1 1
row  64 : 1 1
row  65 : 1 1
row  66 : 0 0
row  67 : 0 0
row  68 : 0 0
row  69 : 0 0
row  70 : 1 1
row  71 : 0 0
row  72 : 0 0
row  73 : 0 0
row  74 : 0 0
row  75 : 0 0
row  76 : 0 0
row  77 : 1 1
row  78 : 0 0
row  79 : 1 1
row  80 : 1 1
row  81 : 0 0
row  82 : 1 1
row  83 : 0 0
row  84 : 1 1
row  85 : 1 1
row  86 : 0 0
row  87 : 1 1
row  88 : 1 1
row  89 : 1 1
row  90 : 1 1
row  91 : 0 0
row  92 : 1 1
row  93 : 1 1
row  94 : 1 1
row  95 : 0 0
row  96 : 0 0
row  97 : 0 0
row  98 : 1 1
row  99 : 0 0
row 100 : 1 1
row 101 : 1 1
row 102 : 1 1
row 103 : 1 1
row 104 : 0 0
row 105 : 0 0
row 106 : 0 0
row 107 : 1 1
row 108 : 1 1
row 109 : 1 1
row 110 : 1 1
row 111 : 1 1
row 112 : 1 1
row 113 : 1 1
row 114 : 1 1
row 115 : 1 1
row 116 : 1 1
row 117 : 0 0
row 118 : 1 1
row 119 : 0 0
row 120 : 1 1
row 121 : 1 1
row 122 : 0 0
row 123 : 1 1
row 124 : 0 0
row 125 : 1 1
row 126 : 1 1
row 127 : 0 0
row 128 : 1 1
row 129 : 0 0
row 130 : 1 1
row 131 : 1 1
row 132 : 1 1
row 133 : 0 0
row 134 : 0 0
row 135 : 0 0
row 136 : 1 1
row 137 : 0 0
row 138 : 1 1
row 139 : 1 1
row 140 : 0 0
row 141 : 0 0
row 142 : 0 0
row 143 : 1 1
row 144 : 0 0
row 145 : 0 0
row 146 : 0 0
row 147 : 0 0
row 148 : 0 0
row 149 : 1 1
row 150 : 0 0
row 151 : 1 1
row 152 : 0 0
row 153 : 0 0
row 154 : 1 1
row 155 : 1 1
row 156 : 0 0
row 157 : 1 1
row 158 : 1 1
row 159 : 1 1
row 160 : 0 0
row 161 : 0 0
row 162 : 0 0
row 163 : 0 0
row 164 : 0 0
row 165 : 1 1
row 166 : 1 1
row 167 : 0 0
row 168 : 1 1
row 169 : 0 0
row 170 : 0 0
row 171 : 1 1
row 172 : 0 0
row 173 : 0 0
row 174 : 0 0
row 175 : 1 1
row 176 : 0 0
row 177 : 1 1
row 178 : 0 0
row 179 : 1 1
row 180 : 1 1
row 181 : 1 1
row 182 : 1 1
row 183 : 1 1
row 184 : 1 1
row 185 : 1 1
row 186 : 0 0
row 187 : 0 0
row 188 : 1 1
row 189 : 0 0
row 190 : 1 1
row 191 : 0 0
row 192 : 0 0
row 193 : 0 0
row 194 : 1 1
row 195 : 1 1
row 196 : 1 1
row 197 : 1 1
row 198 : 1 1
row 199 : 1 1
row 200 : 0 0
row 201 : 1 1
row 202 : 0 0
row 203 : 0 0
row 204 : 0 0
row 205 : 1 1
row 206 : 1 1
row 207 : 0 0
row 208 : 1 1
row 209 : 1 1
row 210 : 1 1
row 211 : 0 0
row 212 : 1 1
row 213 : 1 1
row 214 : 0 0
row 215 : 1 1
row 216 : 1 1
row 217 : 0 0
row 218 : 1 1
row 219 : 1 1
row 220 : 0 0
row 221 : 1 1
row 222 : 1 1
row 223 : 0 0
row 224 : 0 0
row 225 : 1 1
row 226 : 1 1
row 227 : 1 1
row 228 : 1 1
row 229 : 1 1
row 230 : 1 1
row 231 : 1 1
row 232 : 1 1
row 233 : 0 0
row 234 : 1 1
row 235 : 1 1
row 236 : 1 1
row 237 : 1 1
row 238 : 1 1
row 239 : 1 1
row 240 : 1 1
row 241 : 1 1
row 242 : 0 0
row 243 : 1 1
row 244 : 1 1
row 245 : 0 0
row 246 : 0 0
row 247 : 1 1
row 248 : 1 1
row 249 : 0 0
row 250 : 1 1
row 251 : 0 0
row 252 : 1 1
row 253 : 0 0
row 254 : 0 0
row 255 : 0 0
row 256 : 1 1
row 257 : 0 0
row 258 : 0 0
row 259 : 1 1
row 260 : 1 1
row 261 : 1 1
row 262 : 0 0
row 263 : 0 0
row 264 : 0 0
row 265 : 1 1
row 266 : 1 1
row 267 : 0 0
row 268 : 0 0
row 269 : 0 0
row 270 : 1 1
row 271 : 1 1
row 272 : 1 1
row 273 : 1 1
row 274 : 0 0
row 275 : 0 0
row 276 : 1 1
row 277 : 1 1
row 278 : 1 1
row 279 : 0 0
row 280 : 1 1
row 281 : 1 1
row 282 : 1 1
row 283 : 1 1
row 284 : 1 1
row 285 : 1 1
row 286 : 0 0
row 287 : 0 0
row 288 : 1 1
row 289 : 1 1
row 290 : 0 0
row 291 : 0 0
row 292 : 0 0
row 293 : 0 0
row 294 : 0 0
row 295 : 0 0
row 296 : 0 0
row 297 : 0 0
row 298 : 1 1
row 299 : 0 0
row 300 : 0 0
row 301 : 0 0
row 302 : 1 1
row 303 : 0 0
row 304 : 1 1
row 305 : 1 1
row 306 : 1 1
row 307 : 0 0
row 308 : 1 1
row 309 : 0 0
row 310 : 1 1
row 311 : 1 1
row 312 : 0 0
row 313 : 0 0
row 314 : 0 0
row 315 : 1 1
row 316 : 1 1
row 317 : 0 0
row 318 : 0 0
row 319 : 0 0
row 320 : 0 0
row 321 : 1 1
row 322 : 0 0
row 323 : 1 1
row 324 : 0 0
row 325 : 1 1
row 326 : 0 0
row 327 : 0 0
row 328 : 1 1
row 329 : 1 1
row 330 : 1 1
row 331 : 1 1
row 332 : 1 1
row 333 : 0 0
row 334 : 1 1
row 335 : 1 1
row 336 : 0 0
row 337 : 0 0
row 338 : 1 1
row 339 : 0 0
row 340 : 0 0
row 341 : 1 1
row 342 : 1 1
row 343 : 0 0
row 344 : 1 1
row 345 : 1 1
row 346 : 1 1
row 347 : 0 0
row 348 : 0 0
row 349 : 1 1
row 350 : 1 1
row 351 : 1 1
row 352 : 1 1
row 353 : 1 1
row 354 : 0 0
row 355 : 1 1
row 356 : 0 0
row 357 : 1 1
row 358 : 1 1
row 359 : 0 0
row 360 : 0 0
row 361 : 1 1
row 362 : 1 1
row 363 : 1 1
row 364 : 0 0
row 365 : 1 1
row 366 : 0 0
row 367 : 1 1
row 368 : 1 1
row 369 : 1 1
row 370 : 1 1
row 371 : 0 0
row 372 : 0 0
row 373 : 1 1
row 374 : 1 1
row 375 : 1 1
row 376 : 1 1
row 377 : 1 1
row 378 : 1 1
row 379 : 1 1
row 380 : 0 0
row 381 : 1 1
row 382 : 1 1
row 383 : 1 1
row 384 : 0 0
row 385 : 1 1
row 386 : 0 0
row 387 : 1 1
row 388 : 1 1
row 389 : 1 1
row 390 : 1 1
row 391 : 0 0
row 392 : 1 1
row 393 : 0 0
row 394 : 0 0
row 395 : 0 0
row 396 : 1 1
row 397 : 1 1
row 398 : 0 0
row 399 : 1 1
row 400 : 0 0
row 401 : 0 0
row 402 : 0 0
row 403 : 1 1
row 404 : 0 0
row 405 : 0 0
row 406 : 1 1
row 407 : 0 0
row 408 : 0 0
row 409 : 1 1
row 410 : 1 1
row 411 : 1 1
row 412 : 1 1
row 413 : 1 1
row 414 : 1 1
row 415 : 1 1
row 416 : 1 1
row 417 : 1 1
row 418 : 1 1
row 419 : 0 0
row 420 : 1 1
row 421 : 0 0
row 422 : 1 1
row 423 : 0 0
row 424 : 0 0
row 425 : 0 0
row 426 : 1 1
row 427 : 0 0
row 428 : 1 1
row 429 : 0 0
row 430 : 1 1
row 431 : 0 0
row 432 : 1 1
row 433 : 0 0
row 434 : 1 1
row 435 : 1 1
row 436 : 0 0
row 437 : 0 0
row 438 : 1 1
row 439 : 1 1
row 440 : 0 0
row 441 : 1 1
row 442 : 1 1
row 443 : 0 0
row 444 : 1 1
row 445 : 1 1
row 446 : 0 0
row 447 : 0 0
row 448 : 0 0
row 449 : 1 1
row 450 : 0 0
row 451 : 1 1
row 452 : 1 1
row 453 : 1 1
row 454 : 1 1
row 455 : 1 1
row 456 : 1 1
row 457 : 0 0
row 458 : 0 0
row 459 : 0 0
row 460 : 1 1
row 461 : 0 0
row 462 : 0 0
row 463 : 1 1
row 464 : 0 0
row 465 : 1 1
row 466 : 0 0
row 467 : 0 0
row 468 : 1 1
row 469 : 0 0
row 470 : 0 0
row 471 : 0 0
row 472 : 0 0
row 473 : 0 0
row 474 : 1 1
row 475 : 1 1
row 476 : 1 1
row 477 : 1 1
row 478 : 1 1
row 479 : 1 1
row 480 : 0 0
row 481 : 0 0
row 482 : 0 0
row 483 : 0 0
row 484 : 1 1
row 485 : 1 1
row 486 : 1 1
row 487 : 0 0
row 488 : 1 1
row 489 : 1 1
row 490 : 1 1
row 491 : 0 0
row 492 : 1 1
row 493 : 0 0
row 494 : 0 0
row 495 : 0 0
row 496 : 1 1
row 497 : 1 1
row 498 : 0 0
row 499 : 0 0
row 500 : 0 0
row 501 : 1 1
row 502 : 0 0
row 503 : 0 0
row 504 : 0 0
row 505 : 0 0
row 506 : 0 0
row 507 : 1 1
row 508 : 1 1
row 509 : 0 0
row 510 : 0 0
row 511 : 0 0
row 512 : 1 1
row 513 : 1 1
row 514 : 0 0
row 515 : 1 1
row 516 : 1 1
row 517 : 1 1
row 518 : 1 1
row 519 : 0 0
row 520 : 1 1
row 521 : 0 0
row 522 : 1 1
row 523 : 1 1
row 524 : 1 1
row 525 : 1 1
row 526 : 0 0
row 527 : 1 1
row 528 : 0 0
row 529 : 1 1
row 530 : 1 1
row 531 : 0 0
row 532 : 1 1
row 533 : 1 1
row 534 : 0 0
row 535 : 1 1
row 536 : 1 1
row 537 : 0 0
row 538 : 0 0
row 539 : 1 1
row 540 : 0 0
row 541 : 0 0
row 542 : 0 0
row 543 : 1 1
row 544 : 1 1
row 545 : 0 0
row 546 : 0 1   incorrect
row 547 : 0 0
row 548 : 0 0
row 549 : 1 1
row 550 : 0 0
row 551 : 0 0
row 552 : 0 0
row 553 : 1 1
row 554 : 0 0
row 555 : 0 0
row 556 : 0 0
row 557 : 0 0
row 558 : 1 1
row 559 : 0 0
row 560 : 1 1
row 561 : 1 1
row 562 : 1 1
row 563 : 0 0
row 564 : 1 1
row 565 : 1 1
row 566 : 0 0
row 567 : 1 1
row 568 : 1 1
row 569 : 1 1
row 570 : 0 0
row 571 : 1 1
row 572 : 1 1
row 573 : 1 1
row 574 : 0 0
row 575 : 1 1
row 576 : 1 1
row 577 : 1 1
row 578 : 1 1
row 579 : 1 1
row 580 : 0 0
row 581 : 1 1
row 582 : 1 1
row 583 : 0 0
row 584 : 0 0
row 585 : 0 0
row 586 : 0 0
row 587 : 0 0
row 588 : 1 1
row 589 : 1 1
row 590 : 0 0
row 591 : 0 0
row 592 : 0 0
row 593 : 1 1
row 594 : 0 0
row 595 : 1 1
row 596 : 0 0
row 597 : 0 0
row 598 : 1 1
row 599 : 1 1
row 600 : 0 0
row 601 : 0 0
row 602 : 1 1
row 603 : 1 1
row 604 : 1 1
row 605 : 1 1
row 606 : 1 1
row 607 : 1 1
row 608 : 1 1
row 609 : 1 1
row 610 : 0 0
row 611 : 0 0
row 612 : 1 1
row 613 : 0 0
row 614 : 0 0
row 615 : 1 1
row 616 : 0 0
row 617 : 0 0
row 618 : 1 1
row 619 : 1 1
row 620 : 1 1
row 621 : 1 1
row 622 : 0 0
row 623 : 0 0
row 624 : 0 0
row 625 : 1 1
row 626 : 1 1
row 627 : 1 1
row 628 : 0 0
row 629 : 0 0
row 630 : 1 1
row 631 : 1 1
row 632 : 1 1
row 633 : 1 1
row 634 : 1 1
row 635 : 1 1
row 636 : 0 0
row 637 : 1 1
row 638 : 0 0
row 639 : 1 1
row 640 : 1 1
row 641 : 1 1
row 642 : 1 1
row 643 : 0 0
row 644 : 1 1
row 645 : 1 1
row 646 : 1 1
row 647 : 1 1
row 648 : 1 1
row 649 : 1 1
row 650 : 1 1
row 651 : 1 1
row 652 : 1 1
row 653 : 1 1
row 654 : 0 0
row 655 : 1 1
row 656 : 1 1
row 657 : 0 0
row 658 : 0 0
row 659 : 1 1
row 660 : 1 1
row 661 : 1 1
row 662 : 1 1
row 663 : 0 0
row 664 : 1 1
row 665 : 1 1
row 666 : 0 0
row 667 : 0 0
row 668 : 0 0
row 669 : 0 0
row 670 : 0 0
row 671 : 0 0
row 672 : 0 0
row 673 : 1 1
row 674 : 1 1
row 675 : 1 1
row 676 : 1 1
row 677 : 1 1
row 678 : 0 0
row 679 : 1 1
row 680 : 1 1
row 681 : 1 1
row 682 : 1 1
row 683 : 0 0
row 684 : 1 1
row 685 : 0 0
row 686 : 1 1
row 687 : 0 0
row 688 : 1 1
row 689 : 0 0
row 690 : 0 0
row 691 : 1 1
row 692 : 0 0
row 693 : 1 1
row 694 : 1 1
row 695 : 1 1
row 696 : 1 1
row 697 : 1 1
row 698 : 1 1
row 699 : 0 0
row 700 : 1 1
row 701 : 0 0
row 702 : 0 0
row 703 : 0 0
row 704 : 1 1
row 705 : 1 1
row 706 : 1 1
row 707 : 0 0
row 708 : 0 0
row 709 : 0 0
row 710 : 0 0
row 711 : 1 1
row 712 : 0 0
row 713 : 1 1
row 714 : 0 0
row 715 : 0 0
row 716 : 0 0
row 717 : 0 0
row 718 : 1 1
row 719 : 1 1
row 720 : 1 1
row 721 : 1 1
row 722 : 1 1
row 723 : 0 0
row 724 : 1 1
row 725 : 1 1
row 726 : 1 1
row 727 : 0 0
row 728 : 1 1
row 729 : 0 0
row 730 : 1 1
row 731 : 0 0
row 732 : 1 1
row 733 : 0 0
row 734 : 1 1
row 735 : 1 1
row 736 : 0 0
row 737 : 1 1
row 738 : 1 1
row 739 : 1 1
row 740 : 0 0
row 741 : 1 1
row 742 : 1 1
row 743 : 1 1
row 744 : 1 1
row 745 : 0 0
row 746 : 0 0
row 747 : 0 0
row 748 : 0 0
row 749 : 1 1
row 750 : 0 0
row 751 : 0 0
row 752 : 0 0
row 753 : 1 1
row 754 : 0 0
row 755 : 1 1
row 756 : 1 1
row 757 : 0 0
row 758 : 1 1
row 759 : 1 1
row 760 : 0 0
row 761 : 0 0
row 762 : 0 0
row 763 : 0 0
row 764 : 0 0
row 765 : 1 1
row 766 : 1 1
row 767 : 0 0
row 768 : 0 0
row 769 : 1 1
row 770 : 0 0
row 771 : 0 0
row 772 : 1 1
row 773 : 1 1
row 774 : 0 0
row 775 : 1 1
row 776 : 0 0
row 777 : 1 1
row 778 : 1 1
row 779 : 1 1
row 780 : 0 0
row 781 : 0 0
row 782 : 1 1
row 783 : 1 1
row 784 : 0 0
row 785 : 0 0
row 786 : 1 1
row 787 : 0 0
row 788 : 0 0
row 789 : 1 1
row 790 : 0 0
row 791 : 0 0
row 792 : 0 0
row 793 : 0 0
row 794 : 1 1
row 795 : 1 1
row 796 : 1 1
row 797 : 0 0
row 798 : 0 0
row 799 : 1 1
row 800 : 0 0
row 801 : 1 1
row 802 : 1 1
row 803 : 0 0
row 804 : 0 0
row 805 : 1 1
row 806 : 0 0
row 807 : 1 1
row 808 : 1 1
row 809 : 1 1
row 810 : 0 0
row 811 : 1 1
row 812 : 0 1   incorrect
row 813 : 0 0
row 814 : 0 0
row 815 : 1 1
row 816 : 1 1
row 817 : 1 1
row 818 : 1 1
row 819 : 1 1
row 820 : 0 0
row 821 : 1 1
row 822 : 0 0
row 823 : 0 0
row 824 : 0 0
row 825 : 0 0
row 826 : 1 1
row 827 : 1 1
row 828 : 1 1
row 829 : 1 1
row 830 : 1 1
row 831 : 0 0
row 832 : 0 0
row 833 : 1 1
row 834 : 0 0
row 835 : 1 1
row 836 : 1 1
row 837 : 1 1
row 838 : 1 1
row 839 : 1 1
row 840 : 0 0
row 841 : 1 1
row 842 : 1 1
row 843 : 1 1
row 844 : 1 1
row 845 : 0 0
row 846 : 1 1
row 847 : 1 1
row 848 : 1 1
row 849 : 0 0
row 850 : 0 0
row 851 : 1 1
row 852 : 0 0
row 853 : 1 1
row 854 : 1 1
row 855 : 1 1
row 856 : 1 1
row 857 : 0 0
row 858 : 1 1
row 859 : 1 1
row 860 : 0 0
row 861 : 0 0
row 862 : 1 1
row 863 : 1 1
row 864 : 0 0
row 865 : 0 0
row 866 : 1 1
row 867 : 1 1
row 868 : 0 0
row 869 : 0 0
row 870 : 0 0
row 871 : 1 1
row 872 : 0 0
row 873 : 0 0
row 874 : 1 1
row 875 : 1 1
row 876 : 1 1
row 877 : 0 0
row 878 : 0 0
row 879 : 1 1
row 880 : 0 0
row 881 : 0 0
row 882 : 1 1
row 883 : 1 1
row 884 : 0 0
row 885 : 1 1
row 886 : 0 0
row 887 : 0 0
row 888 : 0 0
row 889 : 0 0
row 890 : 1 1
row 891 : 0 0
row 892 : 0 0
row 893 : 0 0
row 894 : 1 1
row 895 : 1 1
row 896 : 0 0
row 897 : 1 1
row 898 : 0 0
row 899 : 0 0
row 900 : 1 1
row 901 : 1 1
row 902 : 1 1
row 903 : 1 1
row 904 : 0 0
row 905 : 1 1
row 906 : 1 1
row 907 : 1 1
row 908 : 1 1
row 909 : 1 1
row 910 : 0 0
row 911 : 0 0
row 912 : 0 0
row 913 : 1 1
row 914 : 0 0
row 915 : 1 1
row 916 : 1 1
row 917 : 0 0
row 918 : 0 0
row 919 : 0 0
row 920 : 0 0
row 921 : 1 1
row 922 : 1 1
row 923 : 1 1
row 924 : 1 1
row 925 : 0 0
row 926 : 1 1
row 927 : 1 1
row 928 : 1 1
row 929 : 1 1
row 930 : 1 1
row 931 : 0 0
row 932 : 0 0
row 933 : 0 0
row 934 : 1 1
row 935 : 0 0
row 936 : 0 0
row 937 : 1 1
row 938 : 1 1
row 939 : 1 1
row 940 : 0 0
row 941 : 1 1
row 942 : 1 1
row 943 : 0 0
row 944 : 1 1
row 945 : 0 1   incorrect
row 946 : 0 0
row 947 : 1 1
row 948 : 1 1
row 949 : 1 1
row 950 : 0 0
row 951 : 1 1
row 952 : 0 0
row 953 : 1 1
row 954 : 1 1
row 955 : 0 0
row 956 : 0 0
row 957 : 0 0
row 958 : 1 1
row 959 : 1 1
row 960 : 1 1
row 961 : 1 1
row 962 : 1 1
row 963 : 0 0
row 964 : 0 0
row 965 : 1 1
row 966 : 1 1
row 967 : 1 1
row 968 : 1 1
row 969 : 0 0
row 970 : 0 0
row 971 : 1 1
row 972 : 1 1
row 973 : 0 0
row 974 : 0 0
row 975 : 0 0
row 976 : 1 1
row 977 : 1 1
row 978 : 1 1
row 979 : 0 0
row 980 : 0 0
row 981 : 0 0
row 982 : 1 1
row 983 : 1 1
row 984 : 1 1
row 985 : 1 1
row 986 : 0 0
row 987 : 1 1
row 988 : 0 0
row 989 : 1 1
row 990 : 1 1
row 991 : 1 1
row 992 : 0 0
row 993 : 1 1
row 994 : 1 1
row 995 : 0 0
row 996 : 1 1
row 997 : 1 1
row 998 : 0 0
row 999 : 1 1
row 1000 : 1 1
row 1001 : 0 0
row 1002 : 1 1
row 1003 : 1 1
row 1004 : 1 1
row 1005 : 1 1
row 1006 : 1 1
row 1007 : 0 0
row 1008 : 1 1
row 1009 : 1 1
row 1010 : 1 1
row 1011 : 0 0

正確性は：99.70355731225297％でした

1009

In [39]:
# フィーチャーの重要度を出力するコード
feature_importances = rforest_model.feature_importances_

feature_importances_dict = {}
for i, importance in enumerate(feature_importances):
  perc = importance * 100
  feature_importances_dict[AE_FILD_df_idf.columns[i]] = perc

sorted_dict = {}
sorted_keys = sorted(feature_importances_dict, key=feature_importances_dict.get)
for w in sorted_keys:
    sorted_dict[w] =  feature_importances_dict[w]
  
for keys in sorted_dict.keys():
  print(f"フィーチャー名：{keys:>12s}は出力データの結果に{sorted_dict[keys]:>7.2f}%関与しています")

フィーチャー名：    IL-12P70は出力データの結果に   0.00%関与しています
フィーチャー名：       IL-17は出力データの結果に   0.00%関与しています
フィーチャー名：        IL-9は出力データの結果に   0.00%関与しています
フィーチャー名：        IL-2は出力データの結果に   0.00%関与しています
フィーチャー名：        IL-3は出力データの結果に   0.00%関与しています
フィーチャー名：        TNFbは出力データの結果に   0.00%関与しています
フィーチャー名：Collagen-diseaseは出力データの結果に   0.04%関与しています
フィーチャー名：        IPAFは出力データの結果に   0.04%関与しています
フィーチャー名：         sexは出力データの結果に   0.05%関与しています
フィーチャー名：       TGF-aは出力データの結果に   0.05%関与しています
フィーチャー名：   emphysemaは出力データの結果に   0.06%関与しています
フィーチャー名：      IL-36βは出力データの結果に   0.09%関与しています
フィーチャー名：Baseline-ILDは出力データの結果に   0.11%関与しています
フィーチャー名：  BAL(Eos-%)は出力データの結果に   0.35%関与しています
フィーチャー名：BAL(Lymph-%)は出力データの結果に   0.37%関与しています
フィーチャー名：Brinkman-Indexは出力データの結果に   0.37%関与しています
フィーチャー名：        KL-6は出力データの結果に   0.39%関与しています
フィーチャー名：         ageは出力データの結果に   0.39%関与しています
フィーチャー名：        IL-8は出力データの結果に   0.40%関与しています
フィーチャー名：        IL-4は出力データの結果に   0.40%関与しています
フィーチャー名：       TGFB2は出力データの結果に   0.40%関与しています
フィーチャー名：  BAL(CD4/8)は出力データの結果に   0.41%関与しています
フィーチャー名：         GROは出力データの結果に   0.41%関与しています
フィーチャー名：      sCD40Lは出力データの結果に   0.41%関与しています
フィーチャー名：       MMP-1は出力データの結果に   0.41%関与しています
フィーチャー名：          IDは出力データの結果に   0.42%関与しています
フィーチャー名：       MCP-3は出力データの結果に   0.42%関与しています
フィーチャー名：       FGF-2は出力データの結果に   0.42%関与しています
フィーチャー名：    BAL(M-%)は出力データの結果に   0.42%関与しています
フィーチャー名：        IL-6は出力データの結果に   0.43%関与しています
フィーチャー名：         CRPは出力データの結果に   0.43%関与しています
フィーチャー名：        TNFaは出力データの結果に   0.43%関与しています
フィーチャー名：        VEGFは出力データの結果に   0.44%関与しています
フィーチャー名：       MMP-7は出力データの結果に   0.44%関与しています
フィーチャー名：       TGFB1は出力データの結果に   0.44%関与しています
フィーチャー名：   P/F-ratioは出力データの結果に   0.44%関与しています
フィーチャー名： FRACTALKINEは出力データの結果に   0.46%関与しています
フィーチャー名：      IFN-a2は出力データの結果に   0.46%関与しています
フィーチャー名：         MDCは出力データの結果に   0.46%関与しています
フィーチャー名：      IL-1RAは出力データの結果に   0.46%関与しています
フィーチャー名：       IP-10は出力データの結果に   0.46%関与しています
フィーチャー名：    IL-12P40は出力データの結果に   0.47%関与しています
フィーチャー名：       IL-10は出力データの結果に   0.47%関与しています
フィーチャー名：       IL-1aは出力データの結果に   0.47%関与しています
フィーチャー名：       MCP-1は出力データの結果に   0.47%関与しています
フィーチャー名：     EOTAXINは出力データの結果に   0.47%関与しています
フィーチャー名：        IL-5は出力データの結果に   0.48%関与しています
フィーチャー名：         EGFは出力データの結果に   0.49%関与しています
フィーチャー名：      Flt-3Lは出力データの結果に   0.50%関与しています
フィーチャー名：       IFN-gは出力データの結果に   0.50%関与しています
フィーチャー名：       G-CSFは出力データの結果に   0.50%関与しています
フィーチャー名：         LDHは出力データの結果に   0.50%関与しています
フィーチャー名：        IL-7は出力データの結果に   0.52%関与しています
フィーチャー名：      GM-CSFは出力データの結果に   0.54%関与しています
フィーチャー名：BAL(neutro-%)は出力データの結果に   0.54%関与しています
フィーチャー名：      MIP-1bは出力データの結果に   0.56%関与しています
フィーチャー名：       TGFB3は出力データの結果に   0.61%関与しています
フィーチャー名：       IL-1bは出力データの結果に   0.62%関与しています
フィーチャー名：       IL-13は出力データの結果に   0.63%関与しています
フィーチャー名：       IL-15は出力データの結果に   0.63%関与しています
フィーチャー名：smoking-statusは出力データの結果に   2.14%関与しています
フィーチャー名：      MIP-1aは出力データの結果に   2.73%関与しています
フィーチャー名：90day-mortalityは出力データの結果に  73.02%関与しています